Mendel.ErrorPage=function(){return{init:function(){var c=$("#md-error-search-query").focus();Mendel.Autocomplete.init(c,function(c,a){var b=$.isString(a)?"/search?query="+a:a.url;Mendel.utils.Browser.setDocumentLocation(b)},{dropDownClass:"md-error-autocomplete"});Mendel.EngagementStrip.init($("#md-engagement-strip"))}}}();
Mendel.ExpertsPage=function(){var c,d,a=function(){for(var b=[],a=$(".expert-tile").length,c=0;c<a;c++)b[c]=c+1;b=Mendel.Misc.shuffle(b);for(c=0;c<a;c++)setTimeout(function(a){return function(){$(".expert-tile-"+b[a]).animate({opacity:1},400)}}(c),60*c)},b=function(b){$UI.Utils.ajax("/experts/ajax/"+b,{success:function(b){d.html(b);Mendel.config.isMobile&&window.scrollTo(0,0);c.show()}})},e=function(){c.hide()};return{init:function(){$("#experts-tiles").uiDelegate(".expert-tile-content","click",function(){b(this.attr("data-expert-id"))},
!0);d=$("#md-expert-info").$uiModalOverlay({backgroundColor:"505050",className:"md-modal-overlay"}).uiDelegate(".md-overlay-close-button","click",e);c=d.$uiGetModalOverlay();$UI.isIE&&9>$UI.browser.version||a();var f=Mendel.utils.Url.getParameterValue("featured");f&&b(f)}}}();Mendel.ListPage=function(){return{init:function(){$(".tt-citations").on("click",Mendel.PageToolbarCitations.show)}}}();
Mendel.MediaGalleryPage=function(){return{init:function(){$UI.window.$uiImageLoader();var c=$("#md-gallery-browse-tabs");c[0]&&c.uiDelegate("a","click",function(){if(this.parent().hasClass("active"))return!1})}}}();
if(Mendel.config.isMobile)Mendel.MediaMobilePage=function(){var c,d,a,b,e,f,g,i,h,j,k,n=function(){c=Math.abs(window.orientation)?screen.width:screen.height;d=Math.abs(window.orientation)?screen.height:screen.width;g.parent().css({top:$UI.window.scrollTop(),height:c+"px"});$("figure",g).css("line-height",c+"px");g.css("transform","translate3d(-"+k*d+"px,0,0)").parent().show()},l=function(a){e=0;b=a.originalEvent.touches[0].pageX;i=+new Date;g.css("transition-duration","0")},m=function(a){e=a.originalEvent.touches[0].pageX-
b;j=0==k&&0<e||k==h&&0>e?0.3:1;g.css("transform","translate3d("+-(-e*j+k*d)+"px,0,0)")},o=function(){if(400>+new Date-i&&50<Math.abs(e)||Math.abs(e)>d/2)0<e&&0<k?k-=1:0>e&&k<h&&(k+=1);g.css({transform:"translate3d(-"+k*d+"px,0,0)","transition-duration":"0.2s"});0==e&&f.css("opacity",parseInt(f.css("opacity"))?0:1)};return{init:function(){g=$(".media-gallery-mobile-slides ul");f=g.find($(".close, .count, figcaption"));h=g[0].children.length-1;g.on({touchstart:l,touchmove:m,touchend:o});$(".close",
g).on("click",function(){g.parent().hide()});a=$(".media-gallery-mobile li");a.on("click",function(){k=$(this).index();n()});$(window).on("orientationchange",n);a.one("click",function(){Mendel.utils.LazyLoad(g)})}}}();
Mendel.MediaOverlay=function(){var c,d,a,b,e,f,g,i,h,j,k,n,l={IMAGE:"Image",INTERACTIVE:"Interactive",VIDEO:"Video",AUDIO:"Audio"},m=function(){var c=240+(e.hasImageMap?30:0),f=$UI.window.height(),d=Math.max(f-c,300),c=Math.max($UI.window.width(),900)-(g[0]?180:0),i;if("INTERACTIVE"==e.type)i={w:e.width,h:e.height};else{i=e.width;var h=e.height;if(i>c||h>d){var k=c/i,j=d/h,k=k<j?k:j;i=Math.floor(k*i);i=i>e.width?e.width:i;h=Math.floor(k*h);h=h>e.height?e.height:h;i={w:i,h:h,resized:!0}}else i={w:e.width,
h:e.height,resized:!1}}h=i;i=h.w;switch(e.type){case "IMAGE":d=a.find("img");d.width(h.w).height(h.h);e.hasImageMap&&d.$uiGetImageMap().resize();i+=2;break;case "INTERACTIVE":b.find(".md-media-overlay-flash-scroller").height(Math.min(d,e.height));"DCR"!=e.renditionPaths[0].mimeType&&(i+=20);break;case "VIDEO":a.find("#md-media-overlay-video-player_wrapper").width(h.w).height(h.h),i+=2}a.width(i);i=a.outerWidth(!0);d=Math.max((f-a.outerHeight(!0))/2,0);c=Math.max((c-i)/2,0);a.css({top:d,left:c});g[0]&&
g.css("left",c+i+60).children("iframe").css("marginTop",Math.max((f-602)/2,0))},o=function(b){k&&k.dispose();c.empty().addClass("md-overlay-loading");i&&i[0]&&h.empty();var a=b,a=$UIString.contains(a,"?")?a.replace("?","/content?"):a+"/content";$UI.Utils.ajax(a,{error:function(){c.removeClass("md-overlay-loading").html('<div class="md-media-overlay-error">Error: Please try again later</div><div class="md-media-overlay-close-error">Close</div>').find(".md-media-overlay-close-error").one("click",r)},
success:function(a){c.html(a);p(a,b)}})},p=function(f,d){c.removeClass("md-overlay-loading");a=c.find(".md-media-overlay-content");b=a.find(".md-media-overlay-container");e=eval("("+b.attr("data-info")+")");e.url=Mendel.config.server+d;e.title=c.find(".md-media-overlay-title span:first").text();Mendel.analytics.logFakePageLoad({documentGroup:Mendel.analytics.MEDIA_OVERLAY_PAGE_LOAD,documentLocation:d});j&&1<j.length?q(d):a.find(".md-media-overlay-next-previous").hide();e.hasImageMap&&b.find("img").$uiImageMap({onMapClick:s});
"AUDIO"===e.type?k=new Mendel.MediaPlayer("md-media-overlay-audio-player",e,Mendel.MediaPlayer.AUDIO_PLAYER):"VIDEO"===e.type&&(k=new Mendel.MediaPlayer("md-media-overlay-video-player",e,Mendel.MediaPlayer.VIDEO_PLAYER));m();a.visibility(!0);if(g[0]){var l='<iframe frameborder="0" marginheight="0" marginwidth="0" scrolling="no" width="120" height="600" src="'+(i.attr("data-src")+"/"+Mendel.Ads.getQuantcastInfo()+"/"+(new Date).getMilliseconds()+i.attr("data-src-params"))+'" ></iframe>';h.html(l)}},
s=function(a){return $UI.String.contains(a,"media")?(o(a),!1):!0},r=function(){c&&(d.hide(),g[0]&&g.hide(),k&&k.dispose(),c.empty(),$("#switch-to-darwin").show(),$.isFunction(n)&&n(),$UI.window.unbind("resize.mediaOverlay"))},q=function(b){for(var c=0,e=j.length;c<e;c++){var f=$(j[c]);if($UI.String.contains(f.attr("href"),b)){b=$(0<c?j[c-1]:j[e-1]).attr("href");c=$(c<e-1?j[c+1]:j[0]).attr("href");a.find(".md-media-overlay-previous").attr("href",b).show();a.find(".md-media-overlay-next").attr("href",
c).show();break}}},v=function(b){var d=$(b.target);d.hasClass("mo-email")&&(g[0]&&g.visibility(!1),Mendel.PageToolbarEmail.show(e.url,e.title,"Email this "+l[e.type],t),b.preventDefault());if(d.hasClass("mo-citations")){var i=c.find(".md-media-overlay-citations");i[0]&&f.html(i.show().remove());g[0]&&g.visibility(!1);f.$uiGetModal().show();b.preventDefault()}if(d.closest(".md-media-overlay-previous")[0]||d.closest(".md-media-overlay-next")[0])o(d.closest("a").attr("href")),b.preventDefault();if(d.hasClass("md-media-overlay-close"))return r(),
!1;if(e&&e.hasImageMap){if(d.hasClass("md-media-overlay-mapcap-asm"))return o(d.attr("href")),!1;if(d.closest(".md-media-overlay-map-highlight")[0])return $(".md-media-overlay-map-highlight a").text((a.find("img").$uiGetImageMap().toggle()?"Hide":"Show")+" clickable areas"),!1}},t=function(){g[0]&&g.visibility(!0)};return{open:function(b,a,e){c||(c=$("#md-media-overlay").on("click",v).$uiModalOverlay({backgroundColor:"FFFFFF",className:"md-modal-overlay-white"}).show(),d=c.$uiGetModalOverlay(),g=
$("#md-media-overlay-ad"),g[0]&&(i=$("#media-overlay-ad-iframe"),h=i.contents().find("body")),f=$('<div id="md-media-overlay-citations-container"></div>').appendTo($UI.body).$uiModal({title:"Citations"}).bind("modalclosed",t));j=a;$("#switch-to-darwin").hide();c.toggleClass("md-arrowless",0==a.length);g[0]&&g.show();d.show();o(b);n=e;$UI.window.bind("resize.mediaOverlay",m)},close:r}}();
Mendel.MediaPage=function(){return{init:function(){var c=Mendel.config.mediaInfo;$(".pt-print").toggle("IMAGE"===c.type).children("a").attr("href","/media/print/"+c.id);if(c.hasImageMap){var d=$(".md-media-wrapper img");d.$uiImageMap();$(".md-media-overlay-map-highlight").on("click",function(){$(".md-media-overlay-map-highlight a").text((d.$uiGetImageMap().toggle()?"Hide":"Show")+" clickable areas");return!1})}"AUDIO"===c.type?new Mendel.MediaPlayer("md-media-overlay-audio-player",c,Mendel.MediaPlayer.AUDIO_PLAYER):
"VIDEO"===c.type&&new Mendel.MediaPlayer("md-media-overlay-video-player",c,Mendel.MediaPlayer.VIDEO_PLAYER);Mendel.config.isMobile?Mendel.MediaMobilePage.init():(c=$("#md-gallery-carousel"),c[0]&&(c.$uiCarousel({lazyLoad:!0,resizeImages:!1,arrow:'<div class="md-carousel-arrow"></div>'}).show(),Mendel.analytics.setClickAction($(".md-media-asset-wrapper .ui-carousel-pn"),Mendel.analytics.MEDIA_PAGE_MAIN_ARROWS_CLICK_ACTION),Mendel.analytics.setClickAction($(".ui-carousel-pn",c),Mendel.analytics.MEDIA_PAGE_IMAGE_STRIP_ARROWS_CLICK_ACTION)),
Mendel.utils.UI.setAltBubble())}}}();
Mendel.MediaPlayer=function(c,d,a){var b,e=function(a,c){for(var e={autostart:!0,modes:[],width:c.width,height:c.height},d=0;d<c.renditionPaths.length;d++){var j=c.renditionPaths[d];switch(j.mimeType){case "FLV":e.modes[0]={type:"flash",config:{file:j.path},src:"/resources/files/jwplayer-510.swf"};break;case "YOUTUBE":e.modes[0]={type:"flash",config:{file:j.path},src:"/resources/files/jwplayer-510.swf"};e.modes[1]={type:"html5",config:{file:j.path}};break;case "MP4":e.modes[1]={type:"html5",config:{file:j.path}}}}if(c.poster&&
""!==c.poster)e.image=c.poster;d=$.isDefined(c.mute)&&!0===c.mute;e.mute=d;e["display.showmute"]=d;if(c.adapTv)e.plugins={adaptvjw5:c.adapTv},e.plugins.adaptvjw5.videoplayerid=a+"_wrapper",e.plugins.adaptvjw5.mute=d;jwplayer(a).setup(e);b=a};this.dispose=function(){var a=jwplayer(b);a&&a.remove()};this.pause=function(){var a=jwplayer(b);a&&a.pause()};this.play=function(){var a=jwplayer(b);a&&a.play()};a===Mendel.MediaPlayer.AUDIO_PLAYER?function(a,c){jwplayer(a).setup({autostart:!0,flashplayer:"/resources/files/jwplayer-510.swf",
file:c.renditionPaths[0].path,width:300,height:24,"controlbar.position":"bottom","controlbar.idlehide":!1});b=a}(c,d):a===Mendel.MediaPlayer.VIDEO_PLAYER&&e(c,d)};Mendel.MediaPlayer.AUDIO_PLAYER="audio";Mendel.MediaPlayer.VIDEO_PLAYER="video";
(function(c){c.fn.hoverIntent=function(d,a,b){var e={interval:100,sensitivity:7,timeout:0},e="object"===typeof d?c.extend(e,d):c.isFunction(a)?c.extend(e,{over:d,out:a,selector:b}):c.extend(e,{over:d,out:d,selector:a}),f,g,i,h,j=function(a){f=a.pageX;g=a.pageY},k=function(a,b){b.hoverIntent_t=clearTimeout(b.hoverIntent_t);if(Math.abs(i-f)+Math.abs(h-g)<e.sensitivity)return c(b).off("mousemove.hoverIntent",j),b.hoverIntent_s=1,e.over.apply(b,[a]);i=f;h=g;b.hoverIntent_t=setTimeout(function(){k(a,b)},
e.interval)},d=function(a){var b=jQuery.extend({},a),d=this;if(d.hoverIntent_t)d.hoverIntent_t=clearTimeout(d.hoverIntent_t);if("mouseenter"==a.type){if(i=b.pageX,h=b.pageY,c(d).on("mousemove.hoverIntent",j),1!=d.hoverIntent_s)d.hoverIntent_t=setTimeout(function(){k(b,d)},e.interval)}else if(c(d).off("mousemove.hoverIntent",j),1==d.hoverIntent_s)d.hoverIntent_t=setTimeout(function(){d.hoverIntent_t=clearTimeout(d.hoverIntent_t);d.hoverIntent_s=0;e.out.apply(d,[b])},e.timeout)};return this.on({"mouseenter.hoverIntent":d,
"mouseleave.hoverIntent":d},e.selector)}})(jQuery);
Mendel.QuizPage=function(){var c=function(b){var c=["Oops!;Not so fast...;Sorry, pal.;Not quite...;Nope.;Uh-uh.;Aw, shucks.;Whoops...".split(";"),"Nice work!,Excellent!,High Five!,Good job!,Keep it up!,Way to go!,You're a star!,Hooray for you!,Terrific!,Correct!".split(",")],d={question:"QUIZ QUESTION",answer:"QUIZ ANSWER",answerLast:"QUIZ ANSWER LAST",results:"QUIZ RESULTS"},g={};b.currentQuestion=0;b.scoreCard={correct:0,incorrect:0};b.view="question";b.quiz=JSON.parse($.ajax({url:"/quiz/ajax/"+
Mendel.config.quizId,dataType:"JSON",async:!1}).responseText);b.checkAnswer=function(a){b.isCorrect=a===b.question.correct;b.isCorrect?b.scoreCard.correct++:b.scoreCard.incorrect++;b.correctMessage=c[+b.isCorrect][Math.floor(Math.random()*(c[+b.isCorrect].length-0)+0)];b.answered=b.question.answers[a-1];b.currentQuestion<b.quiz.questions.length?(b.nextQuestion="Next",b.ytrk="133"):(b.nextQuestion="See Results",b.ytrk="134");b.setView("answer")};b.setView=function(c){if("question"===c)b.currentQuestion<
b.quiz.questions.length?(b.currentQuestion+=1,b.question=JSON.parse($.ajax({url:"/quiz/ajax/"+Mendel.config.quizId+"/"+b.currentQuestion,dataType:"JSON",async:!1}).responseText)):c="results";"results"===c&&window.setTimeout(a,50);g.documentLocation=b.currentQuestion<b.quiz.questions.length?Mendel.config.sharedUrl.split(window.location.host)[1]+"/"+b.currentQuestion:"/quiz/results/"+b.quiz.id;g.documentGroup="answer"===c&&b.currentQuestion===b.quiz.questions.length?d.answerLast:d[c];Mendel.config.hasAds&&
Mendel.Ads.refreshAllAds();Mendel.analytics.setDocumentGroup(g.documentGroup);Mendel.analytics.logFakePageLoad(g);return b.view=c};b.setView(b.view)},d=function(){var a=$(".md-quiz-browse-dropdown");Mendel.Gigya.showLeaderboard({challenge:"quizmaster"});a.on("change",function(a,b){var b=this.value||b,c="ALL QUIZZES"==b?null:{quizCategory:b.toUpperCase()};Mendel.Gigya.showLeaderboard({challenge:"quizmaster",actionAttributes:c})})},a=function(){var a=$(".pie-container"),c=$(".lt50"),d=$(".gt50"),g=
$(".count"),i=g.attr("data-count"),g=g.attr("data-max"),h=i/g,j=360*h,k=$(".md-quiz-leaderboards .bubble-tabs li"),n;0.5>=h?c.css("transform","rotate("+j+"deg)").toggleClass("filled",!1):(c.toggleClass("filled",!0),d.css("transform","rotate("+(j-180)+"deg)"));for(c=0;c<g;c++)$('<div class="spoke" />').css("transform","rotate("+360*c/g+"deg)").appendTo(a);Mendel.config.isLoggedInAsUser&&gigya.gm.notifyAction({action:"quizComplete",actionAttributes:{quizId:Mendel.config.quizId},callback:function(a){console.log(a)}});
n={challenge:"quizmaster",actionAttributes:{quizId:Mendel.config.quizId}};k.on("click",function(){$(this).toggleClass("active",!0).siblings().toggleClass("active",!1);$(this).attr("data-quiz")?(Mendel.Gigya.showLeaderboard({challenge:"quizmaster"}),Mendel.analytics.logClickAction("302")):(Mendel.Gigya.showLeaderboard(n),Mendel.analytics.logClickAction("301"))});Mendel.config.quizScore=i+" out of "+g;Mendel.Gigya.initQuizShare();Mendel.Gigya.showLeaderboard({challenge:"quizmaster"})};return{init:function(){$UI.window.$uiImageLoader();
var b=$("#md-quiz-browse-tabs");b[0]&&b.uiDelegate("a","click",function(){if(this.parent().hasClass("active"))return!1});var e=$("#md-quiz-answers");if(e[0])e.find("li").on("click",function(a){$("#md-quiz-answer").val($(a.target).closest("li").attr("data-value"));e.submit()});$('[data-ytrk-page*="QUIZ BROWSE"]')[0]&&(Mendel.config.isMobile||Mendel.utils.UI.Dropdown($(".md-quiz-browse-dropdown")),d());$('[data-ytrk-page*="QUIZ RESULTS"]')[0]&&a();c.$inject=["$scope"]},QuizController:c}}();
Mendel.SearchPage=function(){var c,d=1,a,b,e,f,g,i,h=function(){var a=$("#sr-media");a[0]&&(g=a.find("ul"),i=a.width(),g.width(2*i+50),$(".next",c).on("click",function(a){j(1);a.preventDefault()}),$(".prev",c).on("click",function(a){j(-1);a.preventDefault()}))},j=function(c){d+=c;d>a?d=1:1>d&&(d=a);$UI.Utils.ajax({url:"/search/ajax/images",data:b+"&page="+d,success:function(a){-1===c?g.prepend(a).css("left",-i).animate({left:0},{duration:2E3,complete:function(){g.children(":gt(4)").remove()}}):g.append(a).animate({left:-i},
{duration:2E3,complete:function(){g.children(":lt(5)").remove();g.css("left",0)}})}})},k=function(){$("#sr-content > ul > li").not("[id=sr-media]").hoverIntent(function(){var a=$(this);"true"===a.attr("data-has-toc")?(e.css({"line-height":a.height()+"px",height:a.height(),top:a.position().top}).removeClass("active").show(),n(a)):(e.hide(),f.hide(),$UI.window.unbind("mendelSearchPreview"))},function(){})},n=function(a){e.addClass("active").show();f.uiLoad("/search/ajax/preview",{topicId:a.attr("data-topic-id")},
function(b){null==b||""==b?(a.attr("data-has-toc","false"),e.hide()):f.show()})};return{init:function(){c=$("#slider-ctn");a=Math.ceil(c.data("total")/5);$("#search-container");b=$("#searchCriteria").serialize();e=$("#search-preview-trigger");f=$("#search-preview-content");var d=$("#header-global-nav-buttons");f.offset();d.height();h();k()}}}();
Mendel.Arbitrator=function(){return{init:function(){var c=Mendel.utils.Cookies.read("SITE");(null===c||""===c)&&Mendel.utils.Cookies.write("SITE","mendel",900);c=$("#switch-to-darwin");if(c[0])c.on("click",function(){Mendel.utils.Cookies.write("SITE","darwin",900);Mendel.analytics.logClickAction(Mendel.analytics.SWITCH_TO_DARWIN,Mendel.utils.Browser.getDocumentLocation());return!1})}}}();$(Mendel.Arbitrator.init);
Mendel.Autocomplete=function(){var c=function(c){var a=[];if(c)for(var b=0,e=c.length;b<e;b++){var f=c[b];a.push({label:f.title+(f.identifier?' <span class="identifier">('+f.identifier+")</span>":""),value:f.title,url:f.url})}return a};return{init:function(d,a,b){var e=$.extend({},{minLength:2,offset:{x:0,y:0},maxItems:5,transformData:c},b);if($.isUndefined(e.getUrl))e.getUrl=function(a){return{url:"/search/ajax/autocomplete",data:{query:a,nb:e.maxItems}}};d.$uiPlaceholder().$uiAutocomplete(e).bind("autocompleteselected",
a);return d.$uiGetAutocomplete()}}}();Mendel.EngagementStrip=function(){return{init:function(c){c[0]&&(c.$uiCarousel({lazyLoad:!0,arrow:'<div class="md-carousel-arrow"></div>',isMobile:Mendel.config.isMobile}).visibility(!0),Mendel.analytics.setClickAction($(".ui-carousel-pn",c),Mendel.analytics.ENGAGEMENT_STRIP_ARROWS_CLICK_ACTION))}}}();Mendel.Footer=function(){return{init:function(){$(".footer-links dt").on("click",function(){$("~ dd",this).slideToggle("fast")})}}}();$(Mendel.Footer.init);
Mendel.Gigya=function(){var c,d=function(){var a=new gigya.socialize.UserAction,b=[{provider:"facebook"},{provider:"Twitter-tweet",via:"Britannica"},{provider:"googleplus-share"},{provider:"share"}],e=function(){$(".gig-button-container-facebook .gig-button-text").text("Share")},d;a.setTitle(c.title);a.setSubtitle("britannica.com");a.setDescription(c.description);a.addMediaItem({type:"image",src:c.image});a.setLinkBack(c.url);d={containerID:"page-socialbar",shareButtons:b,showCounts:"top",layout:"vertical",
userAction:a,onLoad:e,operationMode:"multiSelect"};a={containerID:"page-socialbar-horizontal",shareButtons:b,userAction:a,onLoad:e,operationMode:"multiSelect"};if(Mendel.config.isMobile)a.showCounts="none",b.pop();Mendel.config.isMobile||gigya.socialize.showShareBarUI(d);gigya.socialize.showShareBarUI(a)},a=function(){var a={categoryID:Mendel.config.page,streamID:Mendel.config.topicId||Mendel.config.quizId,containerID:"gigya-comments",cid:"",deviceType:"auto",context:document.querySelector("#gigya-comments"),
useSiteLogin:!0,onSiteLoginClicked:function(c){b(c,a)}};gigya.comments.showCommentsUI(a)},b=function(a,b,c){if(!Mendel.config.isLoggedInAsUser){var d=a.context.querySelector(".gig-comments-textarea").value;Mendel.Login.showLoginBox({type:Mendel.Login.ADD_COMMENT,callback:function(a){e(d,a,b,c?c:null)}})}},e=function(a,b,c,e){0<a.length?gigya.comments.postComment({categoryID:c.categoryID,commentText:a,streamID:c.streamID,UID:b,callback:function(a){gigya.comments.showCommentsUI(c);!$.isUndefined(e)&&
$.isFunction(e)&&e(a)}}):gigya.comments.showCommentsUI(c);Mendel.Login.closeLoginBox()},f=function(a){var b=$("#show-comments");0<a.commentCount&&b.fadeIn("fast")},g=function(a){var b=$(".alert-error");a.errorDetails?b.text(a.errorDetails).fadeIn("fast"):b.fadeIn("fast")},i=function(){$(".alert-success").fadeIn("fast");window.setTimeout(function(){Mendel.utils.UI.hideSlide($(".md-contribution-bar-slides > div.open"),!1,function(){$(".md-contribution-bar-buttons > div.active").removeClass("active")})},
3E3)},h=function(a){var b={width:200,height:70,containerID:"gigya-connect",showTermsLink:!1,showEditLink:!0,hideGigyaLink:!0};if(a)b.containerID=a;gigya.socialize.showAddConnectionsUI(b)},j=function(){Mendel.analytics.logClickAction("18");$.post("/auth/login/ajax/out",function(a){Mendel.utils.Browser.setDocumentLocation(a)})};return{init:function(){gigya.socialize.addEventHandlers({onLogout:j});c=Mendel.utils.Meta.getOGTags();d();$("#gigya-comments")[0]&&a();$("#gigya-connect")[0]&&h();$("#gigya-connect-welcome")[0]&&
h("gigya-connect-welcome")},setAccountInfo:function(a){gigya.accounts.setAccountInfo(a)},initQuizShare:function(){var a=new gigya.socialize.UserAction,b;a.setTitle("I scored "+Mendel.config.quizScore+" on "+c.title);a.setLinkBack(c.url);a.setDescription(Mendel.config.quizDescription);a.addMediaItem({type:"image",src:Mendel.config.quizThumbnail,href:c.url});b={userAction:a,showEmailButton:!0,showMoreButton:!0,cid:"",deviceType:"auto"};$UI.body.on("click","#gigya-share",function(a){gigya.socialize.showShareUI(b);
a.preventDefault()})},initAskComments:function(){var a=Mendel.config.topicId,c;c={categoryID:"Ask",streamID:a,containerID:"gigya-ask-comments",cid:"",onLoad:function(){var a=$("#gigya-ask-comments");a.find(".gig-comments-commentBox-button-post").text("Ask Question");a.find(".gig-comments-headerText").text("Ask a new question");a.find(".gig-comments-follow").text("Follow replies to my question").attr("data-ytrk","277")},filterTags:"hide-comments",onBeforeCommentSubmitted:function(){$(".alert").hide()},
onCommentSubmitted:function(){gigya.comments.getComments(e);i();Mendel.analytics.logClickAction("270");gigya.gm.notifyAction({action:"contributeQuestion"});gigya.comments.setUserOptions({replyNotifications:"immediate"})},onError:g,context:document.querySelector("#gigya-ask-comments"),useSiteLogin:!0,onSiteLoginClicked:function(a){b(a,c,function(a){0<a.errorCode?g(a):i()})}};var e={categoryID:"Ask",streamID:a,callback:f};gigya.comments.getComments(e);gigya.comments.showCommentsUI(c)},initFeedbackPlugins:function(){var a=
new gigya.socialize.UserAction,e;a.setTitle(c.title);a.setLinkBack(c.url);gigya.socialize.showReactionsBarUI({reactions:[{text:"Inspiring",ID:"inspiring"},{text:"Surprising",ID:"surprising"},{text:"Recommended",ID:"recommended"},{text:"Helpful",ID:"helpful"},{text:"Informative",ID:"informative"}],containerID:"gigya-article-reactions",userAction:a,barID:Mendel.config.topicId+"-"+Mendel.config.topicTitle,showCounts:"top"});e={categoryID:"Feedback",streamID:Mendel.config.topicId,containerID:"gigya-feedback-comments",
cid:"",onLoad:function(){var a=$("#gigya-feedback-comments");a.find(".gig-comments-commentBox-button-post").text("Submit Feedback");a.find(".gig-comments-headerText").text("Submit new feedback");a.find(".gig-comments-follow").text("Follow replies to my feedback")},filterTags:"hide-comments",onCommentSubmitted:function(){Mendel.analytics.logClickAction("272");i();gigya.gm.notifyAction({action:"contributeFeedback"})},onError:g,context:document.querySelector("#gigya-feedback-comments"),useSiteLogin:!0,
onSiteLoginClicked:function(a){b(a,e,function(a){0==a.errorCode?i():g(a)})}};gigya.comments.showCommentsUI(e)},initArticleQuestions:function(a){gigya.comments.showCommentsUI({containerID:"gigya-questions-comments",categoryID:"Ask",streamID:a,onLoad:function(){var a=$("#gigya-ask-comments");a.find(".gig-comments-commentBox-button-post").text("Ask Question");a.find(".gig-comments-headerText").text("Ask a new question");a.find(".gig-comments-follow").text("Follow replies to my question")}})},postComment:e,
showLeaderboard:function(a){var b={containerID:"gigya-leaderboard",period:"all",onError:function(a){console.log(a)},onLoad:function(){for(var a=$(".gig-leaderboard-uid"),b,c,e,d=$(".gig-leaderboard-topUser-container"),f=0;f<a.length;f++)b=a[f].textContent||a[f].innerText,b==Mendel.config.userInfo.userId&&(b=$(a[f]).parents(".gig-leaderboard-topUser-container").addClass("current-user"),c=parseInt(b.prev().children(".gig-leaderboard-rank").text())||null,e=parseInt(b.children(".gig-leaderboard-rank").text())||
null,null!==c&&null!==e&&1<e-c&&b.addClass("distant"));d.removeAttr("onclick")},detailsTemplate:"",userTemplate:'$photo<div class="gig-leaderboard-rank">$rank</div><div class="gig-leaderboard-name">$name</div><div class="gig-leaderboard-points">$points</div><div class="gig-leaderboard-uid">$UID</div>'};if(1160<window.innerWidth)b.totalCount=8;else if(1160>=window.innerWidth&&768<=window.innerWidth)Mendel.config.isMobile?b.totalCount=5:b.totalCount=7;else if(600<=window.screen.width)b.totalCount=6;
else if(480<=window.screen.width)b.totalCount=4;else if(480>window.screen.width)b.totalCount=3;$.extend(b,a);gigya.gm.showLeaderboardUI(b)}}}();Mendel.config.includeGigya&&$(Mendel.Gigya.init);
Mendel.Header=function(){var c=function(){Mendel.Autocomplete.init($("#header-query"),function(a,b){var c=$.isString(b)?"/search?query="+b:b.url;Mendel.utils.Browser.setDocumentLocation(c)});Mendel.analytics.setClickAction($(".ui-autocomplete"),Mendel.analytics.SEARCH_AUTOCOMPLETE_CLICK_ACTION)},d=function(){$UI.body.on("click",".login-link",function(a){!Mendel.config.isMobile&&700<=window.screen.width&&(Mendel.Login.showLoginBox(),a.preventDefault())});var a=$("#md-header-join-link");if(a[0])a.on("click",
function(a){Mendel.Login.showLoginBox({type:Mendel.Login.JOIN_COMMUNITY});a.preventDefault()})},a=function(){var a=$("#header-global-nav-drop-down"),b=$("#header-global-nav-drop-down-content"),c=$("#md-global-nav-arrow"),e=$("#header-global-nav-buttons");$("#header-global-nav-buttons a[data-content-url], #header-global-nav-buttons span[data-content-url]").hoverIntent(function(){var e=$(this);c.css("left",e.position().left+e.outerWidth()/2-20).show();b.uiLoad(e.attr("data-content-url"));a.css("overflow",
"visible").show();Mendel.analytics.logClickAction(e.attr("data-ytrk"));c.toggleClass("selected",e.hasClass("selected"))},function(b){$(b.toElement||b.relatedTarget).closest("#header-global-nav-drop-down")[0]||a.hide()});$("li",e).on({mousedown:function(){c.addClass("selected")},mouseup:function(){c.removeClass("selected")}});$("#header-global-nav").on("mouseleave",function(){a.hide();$("li",e).removeClass("selected")});$("li",e).on("mouseover",function(){$(this).addClass("selected").siblings().removeClass("selected")})},
b=function(){$("#header-global-nav-buttons").on("click",function(){$("> li",this).slideToggle("fast")}).on("click","a",function(a){a.stopPropagation()})},e=function(){var a=$(".header-user-dropdown"),b=$(".header-user-dropdown-menu"),c;a.on({mouseleave:function(){b.trigger("mouseleave")},mouseover:function(){b.show().trigger("mouseover")},click:function(){Mendel.config.isMobile&&b.toggle()}});b.on({mouseleave:function(){c=window.setTimeout(function(){b.hide()},1E3)},mouseover:function(){window.clearTimeout(c)}})};
return{init:function(){c();d();Mendel.config.isMobile?b():a();e()}}}();
Mendel.Login=function(){var c,d,a;return{showLoginBox:function(b){var b=b||{},e=b.type,f=b.callback,b="url="+encodeURIComponent(b.url||Mendel.config.currentUrl);switch(e){case Mendel.Login.ADD_COMMENT:e="/auth/loginbox?"+b+"&comments=true";b="Post a Comment: Login";break;case Mendel.Login.WEBSITE_SUBMISSION_LOGIN:case Mendel.Login.PUBLICATION_SUBMISSION_LOGIN:case Mendel.Login.EDIT_SUBMISSION_LOGIN:case Mendel.Login.EDIT_SUBMISSION_LINK_LOGIN:e="/auth/loginbox/submission/"+e+"?"+b;b="Submit Contribution: Login";
break;case Mendel.Login.JOIN_COMMUNITY:e="/auth/loginbox?j=1&"+b;b="Join Our Community";break;default:e="/auth/loginbox?"+b,b="Login"}c||(c=$("#loginbox-dialog"),d=$("#loginbox-dialog-iframe-container"),a=c.$uiModal().$uiGetModal(),a.getFooter().addClass("loginbox-bottom"));d.empty().html('<iframe id="md-loginbox-iframe" scrolling="no" frameborder="0" marginheight="0" marginwidth="0" src="'+e+'"></iframe>');a.setParameters({title:b}).show();$(window).on("message",function(a){if(-1<a.originalEvent.origin.indexOf(window.location.host)&&
$.isDefined(a.originalEvent.data)){var b=eval("("+a.originalEvent.data+")");b&&$.isDefined(b.returnUrl)&&($.isDefined(f)&&$.isFunction(f)?f(a.originalEvent.data.UID):Mendel.utils.Browser.setDocumentLocation(a.originalEvent.data.returnUrl))}})},closeLoginBox:function(){a.hide()},WEBSITE_SUBMISSION_LOGIN:1,PUBLICATION_SUBMISSION_LOGIN:2,EDIT_SUBMISSION_LOGIN:3,EDIT_SUBMISSION_LINK_LOGIN:6,JOIN_COMMUNITY:4,ADD_COMMENT:5}}();
Mendel.MobileUtils=function(){return{replaceLabels:function(c){var d;$("[type=text]",c).each(function(){this.placeholder=d=$("[for="+this.id+"]").text()})}}}();
Mendel.Overlay=function(c,d){var a,b=function(){a.hide()};(function(){var e=c.uiWrap('<div class="md-overlay '+(c.attr("class")?c.attr("class"):"")+'"></div>');c.attr("class","md-overlay-container");var f=c.attr("title");f&&(c.removeAttr("title"),e.prepend('<div class="md-overlay-title ui-font-sans-ui">'+f+'<div class="md-overlay-close-button">\u00d7</div></div>'),e.find(".md-overlay-close-button").on("click",b));a=e.$uiModalOverlay({backgroundColor:d||"505050",className:"md-modal-overlay"}).$uiGetModalOverlay();
e.show()})();this.show=function(){a.show()};this.hide=b};Mendel.PageToolbarCitations=function(){var c;return{show:function(){$.isUndefined(c)&&(c=new Mendel.Overlay($("#md-citations")),$("#export-citations").$uiTwipsy({method:$UI.METHOD_HOVER,position:$UI.POSITION_BOTTOM,fx:$UI.FX_NONE}));c.show()},hide:function(){$.isDefined(c)&&c.hide()}}}();
Mendel.PageToolbarEmail=function(){var c,d,a=function(){var a,e=$("#md-email-dialog");c=e.$uiForm({title:"",show:!1,onSubmit:function(c){a=c;return!c}}).bind("modalformclosed",function(){a&&($UI.alertBox(null,"The email has been successfully sent."),a=!1);d()}).$uiGetForm();Mendel.config.isMobile&&(1024>screen.width&&768<screen.width||600>screen.width)&&Mendel.MobileUtils.replaceLabels(e)};return{show:function(b,e,f,g){c||a();d=g||function(){};$("#md-email-dialog-url").val(b);$("#md-email-dialog-title").val(e);
c.setParameters({title:f}).show()},hide:function(){c&&c.hide()}}}();Mendel.PageToolbar=function(){return{init:function(){var c=$(".pt-email");if(c[0])c.on("click",function(){Mendel.PageToolbarEmail.show(Mendel.config.sharedUrl,document.title,"Email this page")})}}}();
Mendel.Page=function(){var c=[],d=function(){for(var b=$("[data-position-fixed]"),e=0,d=b.length;e<d;e++){var f=$(b[e]);a(f)}$UI.window.scroll(function(){for(var a=$UI.window.scrollTop(),b=0,e=c.length;b<e;b++)if(c[b].is(":visible")){var d=a>c[b].userdata("y");c[b].toggleClass("position-fixed",d);c[b].prev(".position-fixed-filler").toggle(d)}})},a=function(a){if("absolute"!=a.css("position")){var b="height:"+a.outerHeight(!0)+"px; width:"+a.outerWidth(!0)+"px;";a.before('<div class="ui-hidden position-fixed-filler" style="'+
b+'"></div>')}a.userdata("y",a.offset().top-parseInt(a.attr("data-position-fixed"),10));c.push(a)},b=function(){for(var a=0,b=c.length;a<b;a++){var e=c[a];e.userdata("y",e.offset().top-parseInt(e.attr("data-position-fixed"),10));e.prev(".position-fixed-filler").height(e.outerHeight(!0))}},e=function(){Mendel.utils.Browser.mqlEvent("(max-width: 1159px)",function(){b()})},f=function(){var a=$(".social-welcome, .social-category-preferences");if(a[0]){var b=new Mendel.Overlay(a);a.find(".social-category-list")[0]&&
(Mendel.Social.CategoryPreferences.init(),$(".social-category-list").uiLoad("/social/ajax/category-list").on("click","#save-topics",function(){b.hide()}));b.show();$(".close-overlay").on("click",function(){b.hide()})}},g=function(){if($UI.isIE&&10>$UI.browser.version){var a=$(".projects-promo-300x50-box");a.hoverIntent(function(){a.height(250)},function(){a.height(50)})}};return{init:function(){Mendel.analytics.init();d();e();g();f()},addFixedElement:a,reinitFixedElements:b,resetFixedElements:function(){for(var a=
0,b=c.length;a<b;a++){var e=c[a];e.removeClass("position-fixed");e.prev(".position-fixed-filler").hide()}}}}();if(!this.Mendel.Social)Mendel.Social={};
Mendel.Social.CategoryPreferences=function(){var c=Mendel.config.gigyaCategories||[],d=$(".pp-recommendations"),a=$(".social-category-list"),b=function(){var b=$(".more-topics");$UI.document.on("click",".pp-topic",function(){$(this).toggleClass("selected").promise().done(function(){var a=$(this).attr("data-id");$(this).hasClass("selected")?c.push(a):c.splice($.inArray(a,c),1)})});$UI.document.on("click","#save-topics",function(a){var b;b=c.join();Mendel.Gigya.setAccountInfo({data:{eb_categories:b||
null},callback:Mendel.Social.CategoryPreferences.categorySavedCallback});a.preventDefault()});b.on("click",function(b){Mendel.SocialUserProfilePage.fadeSwitch(d,a);b.preventDefault()});$UI.document.on("click",".cancel-topics",function(b){Mendel.SocialUserProfilePage.fadeSwitch(a,d);Mendel.SocialUserProfilePage.loadCategoryList();b.preventDefault()})};return{init:function(){b()},categorySavedCallback:function(b){var f=$(".pp-topic-controls");if(0==b.errorCode)Mendel.SocialUserProfilePage.loadRecommendations(c),
Mendel.SocialUserProfilePage.fadeSwitch(a,d);else{var g=f.find(".alert");g[0]||(g=$('<span class="alert"></span>').appendTo(f));g.text(b.statusMessage);window.setTimeout(function(){g.fadeOut()},5E3)}}}}();
Mendel.SocialUserProfilePage=function(){var c=$("#submit-comment"),d=$("textarea",c),a=$("button",c),b=$(".cancel-submit"),e=null,f=$(".pp-user-comment"),g=$("blockquote",f),i=$("button",f),h=$(".pp-user-categories"),j=$(".social-category-list"),k=$(".clear-blurb"),n=!1,l=function(){d.on({keyup:function(){250>=this.value.length?a.removeClass("disabled").removeAttr("disabled"):a.addClass("disabled").attr("disabled","disabled")},keydown:function(){if(250<=this.value.length)switch(window.event.keyCode){case 8:case 46:return!0;
default:return!1}}});c.on("submit",function(a,b){e=(n=b||!1)?null:this.elements.comment.value;Mendel.Gigya.setAccountInfo({data:{eb_blurb:e},callback:Mendel.SocialUserProfilePage.submitCommentCallback});a.preventDefault()});b.on("click",function(a){m(c,f);a.preventDefault()});i.on("click",function(a){m(f,c);a.preventDefault()});k.on("click",function(){e=null;c.trigger("submit",!0)})},m=function(a,b){a.fadeOut(100,function(){b.fadeIn(100)})},o=function(a){var b=a||null,a=$(".pp-has-cats"),c=$(".pp-has-no-cats"),
e=$(".pp-user-categories + .more-topics");h.uiLoad("/social/ajax/categories/"+Mendel.config.userProfileId,null,null,!1);b&&(b=0<b.length,h.toggleClass("hidden",!b),a.toggleClass("hidden",!b),c.toggleClass("hidden",b),e.toggleClass("hidden",!b))},p=function(){j[0]&&j.uiLoad("/social/ajax/category-list")};return{init:function(){l();o();Mendel.Social.CategoryPreferences.init();p()},submitCommentCallback:function(){n?(d.val(null),m(f,c)):(g.text(e),m(c,f))},fadeSwitch:m,loadRecommendations:o,loadCategoryList:p}}();
Mendel.TopicContributionForms=function(){var c=function(a){var b=0,c;if(10===a.length){var d=a.substring(9).toUpperCase();if("X"!=d&&isNaN(d))return!1;for(c=0;9>c;c++)b+=parseInt(a.substring(c,c+1),10)*(10-c);b+="X"==d?10:parseInt(d,10);return 0==b%11}if(13===a.length&&!isNaN(a)){for(c=0;12>c;c+=2)b+=parseInt(a.substring(c,c+1),10);for(c=1;12>c;c+=2)b+=3*parseInt(a.substring(c,c+1),10);b+=parseInt(a.substring(12),10);return 0==b%10}return!1},d=function(a){var b=$("#biblio-form").$uiGetForm();a?0===
a.totalItems?b.displayMessage({message:"No publications for this ISBN number",field:$("#biblio-isbn")}):(a=a.items[0],b=a.volumeInfo.authors?a.volumeInfo.authors.join(", "):"",$("#biblio-author-name").val(b),$("#biblio-title").val(a.volumeInfo.title),$("#biblio-date").val(a.volumeInfo.publishedDate),$("#biblio-editor").val(a.volumeInfo.publisher)):b.displayMessage({message:"Unable to retrieve ISBN Information",field:$("#biblio-isbn")})};return{initWebsitesForm:function(a){var b=$("#xlinks-form").$uiForm({dialog:!1,
show:!1,getActionFn:function(){return"/submission/link/"+Mendel.config.topicId},onButtonClick:function(){if("Cancel"==$(this).value())return b.clear(),$.isFunction(a)&&a(),!1;if(!Mendel.config.isLoggedInAsUser)return Mendel.Login.showLoginBox({type:Mendel.Login.WEBSITE_SUBMISSION_LOGIN,callback:function(){Mendel.config.isLoggedInAsUser=!0;Mendel.Login.closeLoginBox();b.submit()}}),{noSubmit:!0}},onSubmit:function(c){if(c)$UI.alertBox("Submit a website","Website submitted."),b.clear(),$.isFunction(a)&&
a();else return"Unable to submit the website. Try again later."}}).$uiGetForm()},initBibliographyForm:function(a){var b=$("#biblio-form"),e=b.$uiForm({dialog:!1,show:!1,getActionFn:function(){return"/submission/publication/"+Mendel.config.topicId},onButtonClick:function(){if("Cancel"==$(this).value())return e.clear(),$.isFunction(a)&&a(),!1;var b=$.trim($("#biblio-isbn").val()),c=$.trim($("#biblio-author-name").val()),d=$.trim($("#biblio-title").val()),f=$("#biblio-agree").prop("checked");if(""==
b&&""==c&&""==d)return $("#biblio-isbn").focus(),{error:"Please enter isbn number or publication author/title"};if(""==b&&""==c&&""!=d)return{error:{field:$("#biblio-author-name"),message:"Enter publication author name"}};if(""==b&&""!=c&&""==d)return{error:{field:$("#biblio-title"),message:"Enter publication title"}};if(f){if(!Mendel.config.isLoggedInAsUser)return Mendel.Login.showLoginBox({type:Mendel.Login.PUBLICATION_SUBMISSION_LOGIN,callback:function(){Mendel.config.isLoggedInAsUser=!0;Mendel.Login.closeLoginBox();
e.submit()}}),{noSubmit:!0}}else return{error:{field:$("#biblio-agree"),message:"This checkbox must be checked"}}},onSubmit:function(b){if(b)$UI.alertBox("Submit a publication","Publication submitted."),e.clear(),$.isFunction(a)&&a();else return"Unable to submit the publication. Try again later."}}).$uiGetForm(),f=$("#biblio-isbn");$("#search-isbn").on("click",function(){var a=$UI.String.replaceAll($.trim(f.val()),"-","");f.val(a);if(""==a)e.displayError({field:f,message:"Please, enter an ISBN number"});
else if(c(a)){var b=$(this).addClass("activated");$UI.Utils.ajax("/proxy/ajax/isbn/"+a,{type:"POST",success:d,error:d,complete:function(){b.removeClass("activated")},dataType:"json"})}else e.displayError({field:f,message:"Invalid ISBN number"})});Mendel.config.isMobile&&(1024>=screen.width&&768<=screen.width||600>=screen.width)&&Mendel.MobileUtils.replaceLabels(b)}}}();
Mendel.ContributionToolbar=function(){var c,d,a,b,e,f,g,i,h,j,k,n=function(){f=$(".md-content-wrapper").outerWidth();b=$(".md-contribution-bar-buttons > div",k);d=$(".md-contribution-bar-slides > div",k).width(f).css(a);e=$(".close",d.parent());j=$(".contribute");g=JSON.parse(localStorage.getItem("contributionBar"))||{};b.on("click",l);if(g.disabledTabs)for(var i in g.disabledTabs)$("#"+i,k).off("click",l).on("click",m);e.on("click",function(){Mendel.utils.UI.hideSlide(h,c,o)});j.on("click",function(){var a=
$(this),b=a.closest(d);if(b.find("[type=checkbox]")[0].checked){b=b[0].id.split("-")[0];if(!g.disabledTabs)g.disabledTabs={};g.disabledTabs[b]=!0;localStorage.contributionBar=JSON.stringify(g)}m(a.hasClass("link"));Mendel.utils.UI.hideSlide(h,c,o)})},l=function(){var a=$(this);if(a.hasClass("disabled"))return!1;i=a;o();var b=this.id;h=$("#"+b+"-slide",k);h.siblings(".open").each(function(a,b){Mendel.utils.UI.hideSlide($(b),c)});h.hasClass("open")?Mendel.utils.UI.hideSlide(h,c):Mendel.utils.UI.showSlide(h,
c,function(){var a=p[b];h[0].hasAttribute("data-content-url")&&h.children(".content").uiLoad(h[0].getAttribute("data-content-url"),{topicId:Mendel.config.topicId},a).parent().removeAttr("data-content-url")})},m=function(a){Mendel.TopicEdit.enable(a)},o=function(){i.siblings(".active").each(function(a,b){$(b).toggleClass("active",!1)});i.toggleClass("active")},p={ask:function(){Mendel.Gigya.initAskComments()},reference:function(){var a=function(){Mendel.utils.UI.hideSlide(h,c,o);$("#biblio-form").$uiGetForm().hideMessages();
$("#xlinks-form").$uiGetForm().hideMessages()};$(".md-contributions-reference .md-reference-forms").$uiTabs().bind("tabselected",function(){$("#biblio-form").$uiGetForm().hideMessages();$("#xlinks-form").$uiGetForm().hideMessages()});Mendel.TopicContributionForms.initBibliographyForm(a);Mendel.TopicContributionForms.initWebsitesForm(a);e.on("click",function(){$("#biblio-form").$uiGetForm().hideMessages();$("#xlinks-form").$uiGetForm().hideMessages()})},feedback:function(){Mendel.Gigya.initFeedbackPlugins()}};
return{init:function(){$("#md-page-toolbar #md-contribution-bar").is(":visible")?(k=$("#md-page-toolbar #md-contribution-bar"),a={left:k.outerWidth()+"px"},c=!1):$("#md-page-toolbar-horizontal #md-contribution-bar").is(":visible")&&(k=$("#md-page-toolbar-horizontal #md-contribution-bar"),a={top:k.outerHeight()+"px"},c=!0);$.isDefined(k)&&n()}}}();
Mendel.TopicDictionary=function(){var c,d,a,b,e=function(e,i,h){$.isDefined(i)&&(c.showInWindow(i,h-150,{x:10,y:10}),b.css({left:c.left()-20,top:h-10}).show(),$UI.window.one("scroll.dictionary",f),$UI.html.one("click.dictionary",f));a.text(e);d.uiLoad("/dictionary/ajax",{query:e},function(){$.isDefined(i)&&c.showInWindow(i,h-150,{x:10,y:10});d.scrollTop(0)})},f=function(){$UI.window.unbind(".dictionary");$UI.body.unbind(".dictionary");c.hide();b.hide()};return{init:function(){$(".topic-content").dblclick(function(){var a=
Mendel.utils.Browser.getSelectedText();if(a){var b=Mendel.utils.Browser.getSelectedTextPosition();e(a,b.x+b.w+10,b.y+b.h/2)}});c=$("#md-topic-dictionary").uiDelegate("a","click",function(a){a.preventDefault();this.hasClass("dictionary-audio")?Mendel.utils.Browser.playAudio(this.attr("href")):e(this.attr("data-query"));return!1});d=$("#md-topic-dictionary-content");a=$("#md-topic-dictionary-title");b=$("#md-topic-dictionary-arrow");$("#md-topic-dictionary-close").on("click",f)},open:e,close:f}}();
Mendel.TopicEdit=function(){var c,d,a,b,e,f,g,i,h,j,k=function(){f=$("#content");h=$("#toc");a=$("#md-edit-link-tab");c=$(".topic-content>section").$uiEditor({toolbar:$("#md-edit-toolbar-edit .md-edit-toolbar-styles")}).bind("editormodified",n);$("#md-edit-cancel").on("click",r);d=$("#md-edit-submit").on("click",x);i=$("#md-edit-toolbar-tabs").$uiTabs().$uiGetTabs();g=$("#md-edit-toolbar-link-query").bind("mousedown",l).bind("focus",function(){setTimeout(function(){$UI.html.one("click.editmode",function(){m(!0)})},
100)});j=Mendel.Autocomplete.init(g,B,{maxItems:10,dropDownClass:"md-edit-link-autocomplete"});if(h[0]){var b=function(){h.hide()};h.on("click",function(a){a.stopPropagation()}).find(".topic-toc-close").on("click",b);var e=$("#md-edit-help-toc");e.on("click",function(){var a=e.offset();h.css({top:a.top-$UI.window.scrollTop(),left:a.left-5-h.outerWidth()}).toggle();h.is(":visible")&&($UI.html.one("click.editmode",b),$UI.window.one("scroll.editmode",b));return!1})}var k;$("#md-edit-help-tips").on("click",
function(){k||(k=new Mendel.Overlay($("#md-edit-editing-tips"),"transparent"));k.show();return!1})},n=function(){b||(w(!0),s(!0));e=b=!0;var a=$("#empty-section-stub-warning");a[0]&&a.is(":visible")&&a.fadeOut("fast")},l=function(){null!=$UI.EditorUtils.getSelection()&&($UI.EditorUtils.sendCommand({command:"backgroundColor",param:"#106596"}),$UI.EditorUtils.sendCommand({command:"ForeColor",param:"#FFFFFF"}),$UI.EditorUtils.saveCurrentSelection())},m=function(a){a&&$UI.EditorUtils.setSavedSelection();
$UI.EditorUtils.sendCommand({command:"backgroundColor",param:"#FFFFFF"});$UI.EditorUtils.sendCommand({command:"ForeColor",param:"#444444"});$UI.isIE&&$(".topic-content font").removeAttr("color");Mendel.utils.Browser.removeTextSelection()},o=function(a){b?$UI.multipleChoiceBox("Leave Edit Mode",'You are about to leave edit mode.<br/>Your changes will be lost unless you select "Submit and Leave".',"Leave the Page|Stay in the Page|Submit and Leave",function(b){switch(b.n){case 0:p(a);Mendel.analytics.logClickAction("287");
break;case 1:Mendel.analytics.logClickAction("288");break;case 2:x(function(){p(a)}),Mendel.analytics.logClickAction("289")}}):p(a)},p=function(a){s(!1);Mendel.utils.Browser.setDocumentLocation(a)},s=function(a){a?($UI.window.bind("beforeunload.editPage",function(){return"Your modifications will be lost if you don't submit them."}),Mendel.utils.Browser.setPageRedirectionHook(o)):($UI.window.unbind("beforeunload.editPage"),Mendel.utils.Browser.setPageRedirectionHook())},r=function(){e?o(Mendel.utils.Browser.getDocumentLocation()):
q()},q=function(){c&&($UI.html.unbind(".editmode"),$UI.window.unbind(".editmode"),$UI.body.removeClass("edit-mode"),f.unbind(".editmode"),$(".disable-on-edit").removeClass("disabled"),h[0]&&(h.show(),t(!1)),c.$uiEditor({enabled:!1}).removeClass("editing"),s(!1),window.scrollTo(0,0),Mendel.Page.resetFixedElements(),Mendel.config.isMobile||v(!1))},v=function(b){!1===b?$(c).unbind(".editDblClick"):$(c).bind("dblclick.editDblClick",function(){var b=Mendel.utils.Browser.getSelectedText();b&&3<=b.length&&
(l(),i.setActiveTab(a),j.search(b))})},t=function(a){if(h[0])for(var b=h.find("a"),c=0,e=b.length;c<e;c++){var d=$(b[c]),f=d.attr("href");d.attr("href",a?Mendel.utils.Url.addParameter("afterLoadAction",3,f):Mendel.utils.Url.removeParameter("afterLoadAction",f))}},w=function(a){a?d.removeAttr("disabled"):d.attr("disabled","true")},x=function(a){$UI.progressBar.show("Submitting modifications");Mendel.config.isIndexEntry?z(a):A(a)},z=function(a){$UI.Utils.ajax("/submission/new/"+Mendel.config.topicId,
{data:{topicTitle:Mendel.config.topicTitle,content:$("#empty-section-stub").html()},cacheData:!1,success:function(b){u(b);$.isFunction(a)&&a()},error:function(){u(!1)},type:"POST"})},A=function(a){for(var b=y(),c=[],e=[],d=[],f=[],g=0,h=b.length;g<h;g++){c.push(b[g].sectionId);var i=b[g].title;i||(i=$("#md-edit-help-toc").is(":visible")?"Introduction":"Article");e.push(i);d.push(b[g].originalContent);f.push(b[g].modifiedContent)}$UI.Utils.ajax("/submission/sections/"+Mendel.config.topicId,{data:{topicTitle:Mendel.config.topicTitle,
sectionIds:c,sectionTitles:e,originalContents:d,modifiedContents:f},cacheData:!1,success:function(b){u(b);$.isFunction(a)&&a()},error:function(){u(!1)},type:"POST"})},u=function(a){$UI.progressBar.hide();a?($UI.alertBox("Thank you for your contribution!","Our editors will review what you've submitted, and if it meets our<br/>criteria, we'll add it to the article.<br/><br/>Please note that our editors may make some formatting changes or<br/>correct any spelling or grammar errors, and may contact you if any<br/>clarifications are needed.",
null,$UI.MessageBox.ICON_NONE),w(!1),b=!1,s(!1),c.$uiGetEditor().resetModifiedFlag()):$UI.alertBox("Submit Modifications","Submission error.<br/>Please try again later",null,$UI.MessageBox.ICON_ERROR)},y=function(){for(var a=[],b=0,e=c.length;b<e;b++){var d=$(c[b]);if(d.$uiGetEditor().isModified()){var f=d.id(),g=d.find(".eb-topic-section-title:first"),g=null!=g[0]?g.text():null;a.push({sectionId:f,title:g,originalContent:d.$uiGetEditor().getOriginalContent(),modifiedContent:d.html()})}}return a},
B=function(a,b){$UI.EditorUtils.setSavedSelection();null!=$UI.EditorUtils.getSelection()&&($UI.EditorUtils.insertLink(b.url),m(),n());g.val("").change()};return{enable:function(e){var d=e?Mendel.Login.EDIT_SUBMISSION_LINK_LOGIN:Mendel.Login.EDIT_SUBMISSION_LOGIN;if(Mendel.config.isLoggedInAsUser){if("ARTICLE"!==Mendel.config.topicPageType){var g=Mendel.config.topicUrl,g=Mendel.utils.Url.addParameter("afterLoadAction",d,g);Mendel.utils.Browser.setDocumentLocation(g)}c||k();i.setActiveTab(e?a:$("#md-edit-edit-tab"));
c.$uiEditor({enabled:!0});w(!1);window.scrollTo(0,0);$UI.body.addClass("edit-mode");f.bind("click.editmode",function(a){if($(a.target).is("a"))return a.preventDefault(),!1});$(".disable-on-edit").addClass("disabled");h[0]&&(h.hide(),t(!0));$(c[0]).focus();b=!1;Mendel.Page.reinitFixedElements();Mendel.config.isMobile||v()}else Mendel.Login.showLoginBox({type:d,url:"ARTICLE"!==Mendel.config.topicPageType?Mendel.config.topicUrl:Mendel.config.currentUrl})},disable:q,cancel:r,submit:x,getModifiedSections:y}}();
Mendel.TopicHistory=function(){var c,d,a,b,e,f,g=function(){f=$("#md-topic-diff").$uiModalOverlay({backgroundColor:"505050",className:"md-modal-overlay"}).uiDelegate(".md-overlay-close-button","click",i).$uiGetModalOverlay();d=$("#md-topic-diff-previous").mousedown(function(){if(!$(this).hasClass("disabled"))return j(-1),!1});a=$("#md-topic-diff-next").mousedown(function(){if(!$(this).hasClass("disabled"))return j(1),!1});c=$("#md-topic-diff-container")},i=function(){f.hide()},h=function(){b=-1;d.removeClass("disabled");
var a=c.find(".diff-html-removed, .diff-html-added");e=[];for(var f=0,g=a.length;f<g;f++){var h=$(a[f]);""!==$.trim(h.html())?e.push(h):h.removeAttr("class")}j(1)},j=function(f){-1!=b&&e[b].removeClass("selected");b=$UI.Integer.limit(b+f,0,e.length-1);c.scrollTop(c.scrollTop()+(e[b].addClass("selected").offset().top-c.offset().top-40));d.toggleClass("disabled",0===b);a.toggleClass("disabled",b===e.length-1)};return{show:function(b,e,i){f||g();$("#md-topic-diff-date").text(e);$("#md-topic-diff-contributor").text(i);
d.addClass("disabled");a.addClass("disabled");c.uiLoad("/topic-history/ajax/diff",{df:b},h);f.show()},hide:i,init:function(){$(".topic-content").on("click",function(a){a=$(a.target);if(a.parents().andSelf().hasClass("topic-history-diff-link")){a.hasClass("topic-history-diff-link")||(a=a.parents(".topic-history-diff-link"));for(var b=a.closest("tr"),c=b.find('[data-type="date"]').text(),b=b.find('[data-type="contributor"]'),e="",d=0;d<b.length;d++)e+=", "+$(b[d]).text();Mendel.TopicHistory.show(a.attr("href"),
c,e.substring(2));window.scrollTo(0,0);return!1}})}}}();
Mendel.PaginatedFullArticle=function(){var c=function(){for(var a=$(".bps-topic-table"),b=0,c=a.length;b<c;b++){var d=$(a[b]),g=d.parent(),i=d.find(".oec_table"),h=d.find(".oec-table-wrapper");g.width(g.closest(".topic-content").width());g=Math.min(g.width()-2,i.width());d.width(g).visibility(!0);i.width()>h.width()&&(d=$('<div class="bps-topic-table-scroll-top"><div></div></div>').width(d.width()).insertBefore(h),d.children("div").width(i.width()),d.scroll(function(a,b){return function(){b.scrollLeft(a.scrollLeft())}}(d,
h)),h.scroll(function(a,b){return function(){a.scrollLeft(b.scrollLeft())}}(d,h)))}},d=function(){$(".topic-content").on("click",function(a){var b=$(a.target).closest(".bps-topic-inline-table-full-btn");if(b[0]){var c=b.parent(),a=c.next(),d;c.hasAttr("data-full-img")?d=$("#"+c.attr("data-full-img")):(d=a.clone().removeClass().addClass("bps-topic-inline-table-full-image"),$UI.body.append(d),c.attr("data-full-img",d.id()));b.hasClass("bps-topic-inline-table-full-btn-m")?d.animate({width:a.width(),
height:a.height()},function(){d.hide();b.removeClass("bps-topic-inline-table-full-btn-m").children("span").text("See Full Size")}):(c=a.offset(),d.css({top:c.top,left:c.left}).width(a.width()).height(a.height()).show().animate({width:a.attr("width"),height:a.attr("height")},function(){b.addClass("bps-topic-inline-table-full-btn-m").children("span").text("Close")}))}})};return{init:function(){c();d();var a=$("#topic-pagination");a[0]&&a.find("a").$uiTwipsy({method:$UI.METHOD_HOVER,fx:$UI.FX_NONE})}}}();
Mendel.PageToolbarPrint=function(){var c,d=function(a,b){return['<input type="checkbox" id="',a,'" name="section[]" value="',a,'"/><label for="',a,'">',b,"</label>"].join("")};return{init:function(){var a=$("#md-print-dialog"),b=[],e;"GISTED"!==Mendel.config.contentType&&(e=$("#topic-toc .toc-ul .lv1"));for(var f=0,g=e.length;f<g;f++){var i=$(e[f]),h=i.find("a").first().text();b.push(d("toc-"+i.attr("data-section")+"-"+i.attr("data-toc"),h))}if(0===b.length||1===b.length)return!1;b=$(b.join(""));
$("#md-print-dialog-toc").append(b);c=a.$uiForm({show:!1,ajax:!1,resetBeforeShow:!1}).$uiGetForm();var j=a.find("input").prop("checked",!1);$("#md-print-dialog-toc").uiDelegate("input[type=checkbox]","click",function(){$("#md-print-dialog-submit").prop("disabled",!j.is(":checked"))});var k=!1;$("#md-print-dialog-all").on("click",function(){k=!k;$(this).text((k?"Unselect":"Select")+" All");j.prop("checked",k);$("#md-print-dialog-submit").prop("disabled",!k)});return!0},show:function(a){$("#md-print-dialog-citations").val(a);
c.show();return!1},hide:function(){c&&c.hide()}}}();
Mendel.TopicPage=function(){var c=function(){var a=Mendel.utils.Url.getParameterValue("oasmId");if(null!=a){var b=$("#md-media-strip-tab-list-image a").not('[data-ui-carousel-added="true"]');l("/EBchecked/media/"+a,b);Mendel.utils.Browser.modifyCurrentUrl(Mendel.config.sharedUrl)}},d=function(){$("#md-media-strip-tabs")[0]&&$("#md-media-strip-tabs").bind("tabselected",function(a,b){var c=b.content;null==c.$uiGetCarousel()&&(Mendel.config.isMobile?c.$uiCarousel({lazyLoad:!0,resizeImages:!0,isMobile:!0}):
c.$uiCarousel({lazyLoad:!0,resizeImages:!0,arrow:'<div class="md-carousel-arrow"></div>'}),Mendel.analytics.setClickAction(c.find(".ui-carousel-pn"),Mendel.analytics.TOPIC_CAROUSEL_PREVIOUS_NEXT_CLICK_ACTION))}).$uiTabs()},a=function(){$("#md-related-topics-strip")[0]?$("#md-related-topics-tabs").bind("tabselected",function(a,b){var c=b.content;null==c.$uiGetCarousel()&&(c.$uiCarousel({lazyLoad:!0,arrow:'<div class="md-carousel-arrow"></div>',isMobile:Mendel.config.isMobile}).visibility(!0),Mendel.analytics.setClickAction(c.find(".ui-carousel-pn"),
Mendel.analytics.TOPIC_RELATED_PREVIOUS_NEXT_CLICK_ACTION))}).$uiTabs():$("#md-most-popular-topics-list")[0]&&$("#md-most-popular-topics-list .md-carousel-content").$uiCarousel({lazyLoad:!0,arrow:'<div class="md-carousel-arrow"></div>',isMobile:Mendel.config.isMobile}).visibility(!0)},b,e=function(a){if($.isUndefined(b))if("GISTED"===Mendel.config.contentType||!Mendel.PageToolbarPrint.init()){var c="/print/topic/"+Mendel.config.topicId;"GISTED"!==Mendel.config.contentType&&(c+="?citation="+$("#md-citations-types").find('[name="citation-type"]:checked').val());
$(this).attr("href",c);b=!1}else b=!0;b&&(Mendel.PageToolbarPrint.show($("#md-citations-types").find('[name="citation-type"]:checked').val()),a.preventDefault())},f=function(a,b){if(a[0])a.on("click",function(){g(b,a)});else b.show()},g=function(a,b){a.visibility(!1).show();a.hide().visibility(!0).fadeIn("fast",function(){a.find("input:first").focus()});b&&b.hide()},i=function(a,b){a.fadeOut("fast",function(){b.show()})},h=function(){$UI.window.$uiImageLoader({fx:$UI.FX_NONE,onLoad:function(a){a.closest(".bps-assembly-container").width(a.width()).height(a.height())}})},
j,k=function(){var a=$("#md-sidebar-video-ad");a[0]&&(j=new Mendel.MediaPlayer("md-sidebar-video-ad",eval("("+a.attr("data-info")+")"),Mendel.MediaPlayer.VIDEO_PLAYER),setTimeout(function(){var a=$("#md-sidebar-video-companion-ad");a[0]&&!a.find("iframe")[0]&&a.html(adaptvCompanionAdTag).attr("id","md-sidebar-video-companion-ad-loaded")},5E3))},n=function(){$(".topic-content").on("click",function(a){var b=$(a.target).closest(".media-overlay-link");if(b[0]){var c=b.attr("data-type"),c=$("#md-media-strip-tab-list-"+
c);!Mendel.config.isMobile&&480<=window.screen.width&&(l(b.attr("href"),c[0]?c.find("a").not('[data-ui-carousel-added="true"]'):null),a.preventDefault())}})},l=function(a,b){j&&j.pause();Mendel.MediaOverlay.open(a,b,function(){j&&j.play()})},m=function(){var a=$("#topic-navigator");if(a[0]){for(var b=a.find("ul"),c=b.find("li"),d=0,e=0;e<c.length;e++)d+=$(c[e]).outerWidth(!0);b.width(d+2).$uiScrollingDiv({leftArrow:'<div class="topic-navigator-scroll"></div>',rightArrow:'<div class="topic-navigator-scroll"></div>',
increment:"100%"});a.css("overflow","visible");Mendel.analytics.setClickAction($("[data-article]",a),Mendel.analytics.NAVIGATOR_ARTICLE_CLICK_ACTION);Mendel.analytics.setClickAction($("[data-history]",a),Mendel.analytics.NAVIGATOR_EDITS_CLICK_ACTION);Mendel.analytics.setClickAction($("[data-contributors]",a),Mendel.analytics.NAVIGATOR_CONTRIB_CLICK_ACTION);Mendel.analytics.setClickAction($("[data-profile]",a),Mendel.analytics.NAVIGATOR_FACTS_CLICK_ACTION);Mendel.analytics.setClickAction($("[data-bibliography]",
a),Mendel.analytics.NAVIGATOR_BIBLIO_CLICK_ACTION);Mendel.analytics.setClickAction($("[data-websites]",a),Mendel.analytics.NAVIGATOR_WEBSITES_CLICK_ACTION);Mendel.analytics.setClickAction($("[data-questions]",a),Mendel.analytics.NAVIGATOR_QUESTIONS_CLICK_ACTION);Mendel.analytics.setClickAction($("[data-related]",a),Mendel.analytics.NAVIGATOR_RELATED_CLICK_ACTION);Mendel.analytics.setClickAction($("[data-year_in_review]",a),Mendel.analytics.NAVIGATOR_YIR_CLICK_ACTION)}},o=function(){var a=$("#topic-toc"),
b=!1;if(a[0]){var c=a.find(".toc-ul");if(a.find(".lv2")[0]){c.$uiTree({expanded:!1,plusButton:'<span class="topic-toc-plus"></span>',minusButton:'<span class="topic-toc-minus"></span>'});var d=$("#gisted-toc-expand");d[0]&&d.on("click",function(){b=!b;var a=$(this);a.text(b?"Collapse":"Expand");Mendel.analytics.setClickAction(a,b?Mendel.analytics.TOC_COLLAPSE_CLICK_ACTION:Mendel.analytics.TOC_EXPAND_CLICK_ACTION);c.$uiTree({expanded:b})}).show()}for(var a=a.find("a"),d=0,e=a.length;d<e;d++){var f=
$(a[d]);Mendel.analytics.setClickAction(f,(-1<f.attr("href").indexOf("#")?"":"/")+Mendel.analytics.TOC_LINK_CLICK_ACTION)}}};return{init:function(){if("GISTED"!==Mendel.config.contentType)$(".tt-citations").on("click",Mendel.PageToolbarCitations.show);$(".pt-print a").on("click",e);Mendel.ContributionToolbar.init();m();k();Mendel.EngagementStrip.init($("#md-engagement-strip"));switch(Mendel.config.topicPageType){case "ARTICLE":d();a();o();n();h();("PAGINATED"==Mendel.config.contentType||"FULL"==Mendel.config.contentType)&&
Mendel.PaginatedFullArticle.init();break;case "YEAR_IN_REVIEW":$("#md-yblinks").$uiTree({expanded:!1});break;case "WEBSITES":var b=$("#md-xlinks-show-form"),j=$("#xlinks-form-wrapper");f(b,j,Mendel.Login.WEBSITE_SUBMISSION_LOGIN);Mendel.TopicContributionForms.initWebsitesForm(function(){i(j,b)});break;case "BIBLIOGRAPHY":var l=$("#biblio-show-form"),q=$("#biblio-form-wrapper");f(l,q,Mendel.Login.PUBLICATION_SUBMISSION_LOGIN);Mendel.TopicContributionForms.initBibliographyForm(function(){i(q,l)});break;
case "HISTORY":Mendel.TopicHistory.init();break;case "QUESTIONS":Mendel.Gigya.initArticleQuestions(Mendel.config.topicId)}c();if($.isDefined(Mendel.config.afterLoadAction)&&!Mendel.config.isLoggedInAsUser)$UI.alertBox("Action not allowed","You have to be logged in as an individual user to complete this action");else switch($.isDefined(Mendel.config.afterLoadAction)&&Mendel.utils.Browser.modifyCurrentUrl(Mendel.config.sharedUrl),Mendel.config.afterLoadAction){case Mendel.Login.WEBSITE_SUBMISSION_LOGIN:g($("#xlinks-form-wrapper"),
$("#md-xlinks-show-form"));break;case Mendel.Login.PUBLICATION_SUBMISSION_LOGIN:g($("#biblio-form-wrapper"),$("#biblio-show-form"));break;case Mendel.Login.EDIT_SUBMISSION_LOGIN:Mendel.TopicEdit.enable();break;case Mendel.Login.EDIT_SUBMISSION_LINK_LOGIN:Mendel.TopicEdit.enable(!0);break;case Mendel.Login.ADD_COMMENT:$UI.window.scrollTop($("#didnt-know").offset().top)}}}}();if(!Mendel.UI)Mendel.UI={};
Mendel.UI.LazyLoad=function(c){for(var d=[],a=$("img",c),b=0;b<a.length;b++)d.push(a[b]);var e=function(a){var b=a.getAttribute("data-src");if(b)$(a).hide().visibility(!0).attr("src",b).removeAttr("data-src"),a.onload=function(){$(this).fadeIn("fast")}},f=function(){for(var a=0;a<d.length;a++){var b=d[a],h=b.getBoundingClientRect();if(0<=h.left&&h.left<(window.innerWidth||document.documentElement.clientWidth)&&$(b).is(":visible")||0<=h.right&&h.right<(window.innerWidth||document.documentElement.clientWidth)&&
$(b).is(":visible"))e(d[a]),d.splice(a,1)}0===d.length&&c.off("scroll touchmove",f)};c.on({scroll:f,touchmove:f});f();this.checkBounds=f()};(function(c){c.fn.$lazyLoad=function(d){return this.each(function(){Mendel.UI.LazyLoad(c(this),d)})}})(jQuery);if(!Mendel.UI)Mendel.UI={};
Mendel.UI.Swipes=function(){if(Mendel.config.isMobile&&"function"===typeof window.CustomEvent){var c,d,a,b,e,f,g,i=new CustomEvent("swipe",{detail:{},bubbles:!0,cancelable:!0}),h={left:!1,right:!1,up:!1,down:!1};window.addEventListener("touchstart",function(c){a=c.touches[0].pageX;b=c.touches[0].pageY;g=+new Date},!1);window.addEventListener("touchend",function(j){if(400>+new Date-g)e=a-j.changedTouches[0].pageX,f=b-j.changedTouches[0].pageY,c=Math.abs(e),d=Math.abs(f),50<=c&&c>d?0<e?(h.left=!0,h.right=
h.up=h.down=!1):(h.right=!0,h.left=h.up=h.down=!1):50<=d&&d>c?0<f?(h.up=!0,h.left=h.right=h.down=!1):(h.down=!0,h.left=h.right=h.up=!1):h.left=h.right=h.up=h.down=!1;for(var k in h)if(h[k])i.detail.direction=h,i.detail.target=j.target,window.dispatchEvent(i)},!1)}}();if(!Mendel.UI)Mendel.UI={};
Mendel.UI.SwipeShow=function(c,d){var a,b=c.find(".controls"),e=c.find("ul"),f=c.find("li"),g=c.find(".close"),i=c.$uiModalOverlay({opacity:1}).$uiGetModalOverlay(),h,j,k,n=f.length,l=d,m=90===Math.abs(window.orientation)?screen.height:screen.width;$UI.window.on("swipe",function(a){a.originalEvent.detail.direction.left?++l<n?p(l*m,400):l--:a.originalEvent.detail.direction.right&&(0<=--l?p(l*m,400):l++)});$UI.window.on("orientationchange",function(){o()});g.on("click",function(){i.hide()});var o=function(){e.is(":visible")&&
(m=f.width());f.each(function(a){$(this).css("left",a*m)});p(l*m)},p=function(b,c){c?a.css({transform:"translate3d("+-1*b+"px, 0, 0)",transition:"all "+c+"ms ease"}):a.css({transform:"translate3d("+-1*b+"px, 0, 0)",transition:"none"})};a=c.parent();a.on({touchstart:function(a){h=a.originalEvent.touches[0].clientX;j=0},touchmove:function(a){j=h-a.originalEvent.touches[0].clientX;k=l===n-1&&0<j||0===l&&0>j?0.3:1;p(l*m+j*k)},touchend:function(){0!==j?p(l*m,400):b.css({opacity:parseInt(b.css("opacity"))?
0:1})}});o();i.show();e.$lazyLoad()};(function(c){c.fn.$swipeShow=function(d){return this.each(function(){Mendel.UI.SwipeShow(c(this),d)})}})(jQuery);Mendel.UserProfilePage=function(){return{init:function(){var c=$(".md-sidebar-list-all");c.on("click",function(){c.parent().uiLoad(c.attr("href"));return!1})}}}();
Mendel.Ads=function(){var c=function(a){if(Mendel.config.logGoogleGPT&&googletag&&googletag.debug_log.F){$log("[=== GOOGLE GPT Ad log "+(a?"("+a+")":"")+" ===]");for(var a=googletag.debug_log.F,b=0;b<a.length;b++)$log("["+(b+1)+"] "+a[b].toString());$log("[=== End Google GPT Ad log ===]")}},d=function(){if(googletag&&googletag.debug_log.F)googletag.debug_log.F=[]};return{refreshGoogleGPT:function(a){googletag.cmd.push(function(){googletag.pubads().refresh([a]);Mendel.config.logGoogleGPT&&(c(),d())})},
getQuantcastInfo:function(){var a=[],b=Mendel.utils.Cookies.read("__qseg");if(b)for(var b=b.split("|"),c=0;c<b.length;c++){var d=b[c].split("_");1<d.length&&a.push(d[1])}return a.join(",")},displayGoogleGPTLog:c,clearGoogleGPTLog:d,refreshAllAds:function(){googletag.pubads().refresh()}}}();
MendelAnalytics=function(){var c,d=!1,a,b,e=function(a){setTimeout(function(){Mendel.utils.Browser.setDocumentLocation(a)},100)},f=function(b,d){c&&(i("logClickAction",{action:b,documentGroup:a}),$.isDefined(d)&&e(d))},g=function(){c&&i("logPageLoad",{documentGroup:a,fakeParameters:b})},i=function(a,b){for(var c=0;c<Mendel.config.analytics.length;c++)Mendel.analytics[Mendel.config.analytics[c].type][a](b)};return{HOME_CAROUSEL_PREVIOUS_NEXT_CLICK_ACTION:15,SEARCH_AUTOCOMPLETE_CLICK_ACTION:22,TOPIC_CAROUSEL_PREVIOUS_NEXT_CLICK_ACTION:90,
TOC_COLLAPSE_CLICK_ACTION:81,TOC_EXPAND_CLICK_ACTION:120,TOC_LINK_CLICK_ACTION:131,MEDIA_PAGE_MAIN_ARROWS_CLICK_ACTION:160,MEDIA_PAGE_IMAGE_STRIP_ARROWS_CLICK_ACTION:161,TOPIC_RELATED_PREVIOUS_NEXT_CLICK_ACTION:202,NAVIGATOR_H1_CLICK_ACTION:206,NAVIGATOR_ARTICLE_CLICK_ACTION:290,NAVIGATOR_EDITS_CLICK_ACTION:291,NAVIGATOR_CONTRIB_CLICK_ACTION:292,NAVIGATOR_FACTS_CLICK_ACTION:293,NAVIGATOR_BIBLIO_CLICK_ACTION:294,NAVIGATOR_WEBSITES_CLICK_ACTION:295,NAVIGATOR_RELATED_CLICK_ACTION:210,NAVIGATOR_YIR_CLICK_ACTION:211,
NAVIGATOR_QUESTIONS_CLICK_ACTION:286,ENGAGEMENT_STRIP_ARROWS_CLICK_ACTION:249,SWITCH_TO_DARWIN:101,MEDIA_OVERLAY_PAGE_LOAD:"/MEDIA/OVERLAY",init:function(){if(c=0<Mendel.config.analytics.length){d=Mendel.config.logAnalytics;for(var h=0;h<Mendel.config.analytics.length;h++){var i=Mendel.config.analytics[h];Mendel.analytics[i.type].init(i,d);d&&$log(i.type+" Analytics initialized. Config= { click:"+i.click+", page: "+i.page+" }")}a=$UI.html.attr("data-ytrk-page");"undefined"!==typeof a&&$UI.String.contains(a,
"[")&&(b=$UI.String.between(a,"[","]"),a=$UI.String.before(a,"["));a&&(a=$.trim(a),g());h=function(a){var b=$(a.target).closest("[data-ytrk]");if(b[0]){var c=b.attr("data-ytrk"),d;"/"===c.charAt(0)&&(c=c.substring(1),d=b.attr("href"));f(c);d&&(a.preventDefault(),e(d))}};window.addEventListener?$UI.body[0].addEventListener("click",h,!0):$UI.body[0].attachEvent("click",h);if(d){h=$("[data-ytrk]");$log(h.length+" actions:");for(var i=0,k=h.length;i<k;i++)$log("   Action: ["+$(h[i]).attr("data-ytrk")+
"]")}}},setClickAction:function(a,b){c&&a.each(function(){var a=$(this);d&&$log(" Set click action ["+b+"] on ",a);a.attr("data-ytrk",b)})},logClickAction:f,logPageLoad:g,logFakePageLoad:function(a){c&&i("logFakePageLoad",a)},getDocumentGroup:function(){return a},setDocumentGroup:function(b){$UI.html.attr("data-ytrk-page",b);a=b}}}();$.extend(Mendel.analytics,MendelAnalytics);
Mendel.analytics.eb=function(){var c,d;return{init:function(a,b){d=b;c=a},logClickAction:function(){},logPageLoad:function(){},logFakePageLoad:function(a){c.page&&(writeStat(null,{accountId:EBStat.accountId,requestUrl:a.documentLocation,domain:EBStat.domain,hostnameOverride:EBStat.host}),d&&$log("[EB ANALYTICS] - Eb fake pageLoad: "+a.documentLocation))}}}();
Mendel.analytics.google=function(){var c,d,a=function(){_gaq.push(["_setAccount",c.id]);_gaq.push(["_setDomainName","britannica.com"]);_gaq.push(["_setCustomVar",1,"User Type",Mendel.config.userType,3]);_gaq.push(["_setCustomVar",2,"Test Version",Mendel.config.testVersion,2]);Mendel.config.isLoggedInAsUser&&_gaq.push(["_setCustomVar",3,"User Id",Mendel.config.userInfo.userId,3]);_gaq.push(["_setCustomVar",5,"Login Provider",Mendel.config.userInfo.provider,3]);e("Google pageLoad init: Set Custom Variables CV1 ["+
Mendel.config.userType+"] - CV2 ["+Mendel.config.testVersion+"]")},b=function(a,b,c){b=a.replace(/ /g,"/")+b+(c?c:"");_gaq.push(["_trackPageview",b]);e("Google pageLoad init TrackPage: DocumentGroup ["+a+"] -> "+b)},e=function(a){d&&$log("[GOOGLE ANALYTICS] - "+a)};return{init:function(a,b){d=b;c=a},logClickAction:function(a){if(c.click){var b=Mendel.analytics.actionMapping["a_"+a.action];b||(b="Unknown");_gaq.push(["_trackEvent",b+" ("+a.action+")",a.documentGroup]);e("click: action ["+b+" ("+a.action+
") ] - DocGroup ["+a.documentGroup+"]")}},logPageLoad:function(d){c.page&&(a(),b(d.documentGroup,Mendel.utils.Browser.getDocumentLocation(),d.fakeParameters),e("Google pageLoad: "+d.documentGroup+d.documentLocation))},logFakePageLoad:function(d){c.page&&(a(),b(d.documentGroup,d.documentLocation,d.fakeParameters),e("Google pageLoad: "+d.documentGroup+d.documentLocation))}}}();
Mendel.analytics.actionMapping={a_5:"HP - DYN Img",a_6:"HP - DYN Title",a_7:"HP - TOB Img",a_8:"HP - TOB Title",a_9:"HP - TOB Learn More",a_10:"HP - New Rev Link",a_11:"HP - SL Featured Img",a_12:"HP - SL Featured Title",a_126:"HP - Spotlights LM",a_14:"HP - Spotlights Thumbs",a_15:"HP - Spotlight Arrows",a_17:"HDR - Log In",a_18:"HDR - Log Out",a_19:"HDR - Subscribe",a_20:"HDR - My Account",a_21:"HDR - Search",a_22:"HDR - Search Select",a_23:"HDR - Nav Advocacy",a_24:"HDR - Nav Blog",a_25:"HDR - Nav Store",
a_26:"HDR - Nav About Us",a_27:"HDR - School Library Prod",a_127:"HDR - Nav Help",a_128:"HDR - Nav About Ads",a_28:"FTR - Britannica Kids",a_29:"FTR - Merriam Webster",a_30:"FTR - SmartMath",a_31:"FTR - School and Library",a_33:"FTR - Britannica Store",a_34:"FTR - iPhone App",a_35:"FTR - iPad App",a_36:"FTR - Apps Kids",a_37:"FTR - Contact us",a_38:"FTR - Facebook",a_39:"FTR - Twitter",a_40:"FTR - Youtube",a_41:"FTR - Newsletters",a_42:"FTR - RSS",a_43:"FTR - Widgets",a_44:"FTR - Australia Intl",
a_45:"FTR - Brazil Intl",a_47:"FTR - India Intl",a_48:"FTR - Korea Intl",a_49:"FTR - Latin Intl",a_51:"FTR - UK Intl",a_123:"FTR - China Intl",a_124:"FTR - Japan Intl",a_132:"FTR - Publish Ptnr",a_52:"FTR - Syndication",a_53:"FTR - International Pub",a_54:"FTR - Webmaster",a_56:"FTR - Blog Archive",a_57:"FTR - Site Map",a_58:"FTR - Our Contributors",a_59:"FTR - About us",a_129:"FTR - About Ads",a_60:"FTR - Privacy Policy",a_61:"FTR - Terms of Use",a_62:"SP - Search Result",a_63:"SP - Media",a_64:"SP - Media Arrow",
a_65:"SP - Bottom Search",a_66:"SP - Pagination",a_68:"TP - Submit Contribution ",a_69:"TP- Contributors",a_70:"TP- History",a_71:"TP - Export Citations",a_72:"TP - Submit Website",a_73:"TP - Submit Resources",a_74:"TP - TOC Shortcut",a_130:"TP - Pagination Text",a_75:"TP - Pagination Numbers",a_76:"TP-Thumbnails Image",a_77:"TP-Thumbnails Video",a_78:"TP-Thumbnails Audio",a_81:"TP - TOC Expand",a_120:"TP - TOC Collapse",a_131:"TP - TOC Links",a_82:"TP - Rltd People",a_83:"TP - Rltd Places",a_84:"TP - Rltd Topic",
a_85:"TP - See more button",a_86:"TP - Pplr Articles",a_79:"TP-MS TN Image",a_80:"TP-MS TN Video",a_122:"TP-MS TN Audio",a_87:"TP- Image Strip  ",a_88:"TP- Video Strip",a_89:"TP- Audio Strip",a_90:"TP- Media Arrow ",a_94:"Overlay - Arrows",a_95:"Overlay - Enlarge",a_96:"Overlay - Share",a_97:"MediaPg - Enlarge",a_101:"Darwin/Mendel Toggle",a_102:"Toggle - Continue",a_103:"Toggle - Cancel",a_111:"NavTl - Print",a_112:"NavTl - Email",a_113:"NavTl - Share",a_114:"NavTl - FB Like",a_115:"NavTl - Twitter",
a_116:"NavTl - Google+1",a_117:"NavTl - Cite",a_118:"NavTl - FontIncrease",a_119:"NavTl - FontDecrease",a_163:"MediaPg - Related Link",a_164:"Quiz - Lets go",a_133:"Quiz Page - Next",a_134:"Quiz Page - Get Results",a_135:"PopQuizPromo - Item",a_136:"BrowQuiz - Featured Tab",a_138:"BrowQuiz - Recently Add Tab",a_140:"BrowQuiz - By Topic Tab",a_152:"BrowQuiz - Alpha Tab",a_137:"BrowQuiz - Featured Item",a_139:"BrowQuiz - Recently Add Item",a_153:"BrowQuiz - Alpha Item",a_141:"BrowQuiz - Animal Category",
a_142:"BrowQuiz - Art Category",a_143:"BrowQuiz - Geography Category",a_144:"BrowQuiz - History Category",a_145:"BrowQuiz - Language Category",a_146:"BrowQuiz - Literature Category",a_147:"BrowQuiz - Music Category",a_148:"BrowQuiz - PopCulture Category",a_149:"BrowQuiz - Science Category",a_150:"BrowQuiz - Sports Category",a_165:"BrowQuiz - Food",a_166:"BrowQuiz - Mathematics",a_151:"BrowQuiz - By Topic Item",a_159:"ImageGal - Enlarge",a_160:"ImageGal- Main Arrow",a_161:"ImageGal- Arrow Strip",a_167:"ImageGal- Gallery Link",
a_162:"ImagePromoMod- Item",a_154:"ContentPromo - Item 1",a_155:"ContentPromo - Item 2",a_156:"ContentPromo - Item 3",a_157:"ContentPromo - Item 4",a_158:"ContentPromo - Item 5",a_168:"BrowImage- Featured Tab",a_169:"BrowImage- Featured Item",a_170:"BrowImage- Recently Add Tab",a_171:"BrowImage- Recently Add Item",a_172:"BrowImage- Alpha Tab",a_173:"BrowImage- Alpha Item",a_174:"BrowImage- Popular Quiz Item",a_175:"FTR - Quiz",a_176:"FTR - Image Gallery",a_177:"TP- Quiz Strip",a_178:"TP- Lists",a_179:"IGal-Category Tab",
a_180:"IGal-Animal Category",a_181:"IGal-Art Category",a_182:"IGal-Food Category",a_183:"IGal-Geography Category",a_184:"IGal History Category",a_185:"IGal-Language Category",a_186:"IGal-Literature Category",a_187:"IGal-Mathematics Category",a_188:"IGal-Music Category",a_189:"IGal-Culture Category",a_190:"IGal- Science Category",a_191:"IGal- Sports Category",a_192:"List-Top Next",a_193:"List-Bottom Next",a_194:"List-Top Previous",a_198:"List-Bottom Previous",a_195:"Q&A-Left Arrow",a_196:"Q&A-Right Arrow",
a_197:"Q&A-DiveDeeper",a_199:"TP-MS TN Quiz",a_200:"TP-MS TN List",a_201:"FTR - Q&As",a_202:"TP - Rltd Strip Arrows",a_203:"TP - Pplr Articles Strip Arrows",a_204:"TP-Sidebar-CountryDataExpand",a_205:"Tp-Sidebar-Thumb",a_206:"TOCNav-H1Link",a_209:"TOCNav-Contrib",a_210:"TOCNav-Rltd",a_211:"TOCNav-YIR",a_212:"TP-Byline",a_213:"TP-ViewAllContrib",a_214:"NavTl - FB Share",a_215:"List - Byline",a_216:"List - View Contributors",a_217:"BrowList- Featured Tab",a_218:"BrowList- Featured Item",a_219:"BrowList- Recently Add Tab",
a_220:"BrowList- Recently Add Item",a_221:"BrowList- Alpha Tab",a_222:"BrowList- Alpha Item",a_223:"BrowList-Category Tab",a_224:"BrowList-Animals",a_225:"BrowList-Art",a_226:"BrowList-Food",a_227:"BrowList-Geography",a_228:"BrowList-History",a_229:"BrowList-Language",a_230:"BrowList-Lit",a_231:"BrowList-Math",a_232:"BrowList-Music",a_233:"BrowList-PopCulture",a_234:"BrowList-Science",a_235:"BrowList-Sports",a_236:"GlobNav-PopTop",a_237:"GlobNav-Experts",a_238:"GlobNav-Quiz",a_239:"GlobNav-Galleries",
a_240:"GlobNav-List",a_241:"GlobNav-PopTop-Item",a_242:"GlobNav-Experts-Item",a_243:"GlobNav-Quiz-Item",a_244:"GlobNav-Quiz-Cat",a_245:"GlobNav-Galleries-Item",a_246:"GlobNav-Galleries-Cat",a_247:"GlobNav-List-Item",a_248:"GlobNav-List-Cat",a_249:"EngStrip-Arrows",a_250:"EngStrip-Item1",a_251:"EngStrip-Item2",a_252:"EngStrip-Item3",a_253:"EngStrip-Item4",a_254:"EngStrip-Item5",a_255:"EngStrip-Item6",a_256:"EngStrip-Item7",a_257:"EngStrip-Item8",a_258:"EngStrip-Item9",a_259:"EngStrip-Item10",a_260:"EngStrip-Item11",
a_261:"EngStrip-Item12",a_262:"HDR - Join",a_263:"TP - Update",a_264:"TP - Link",a_265:"TP - Ask",a_266:"TP - Reference",a_267:"TP - Feedback",a_268:"TP - Update Interface",a_269:"TP - Link Interface",a_270:"TP - Submit a Question",a_271:"TP - Reference Submit",a_272:"TP - Feedback Submit",a_273:"TP - Exit Update Overlay",a_274:"TP - Exit Link Overlay",a_275:"TP - Look at Other Questions",a_276:"TP - Exit Ask Overlay",a_277:"TP - Follow Ask Replies",a_278:"TP - Exit Ref Overlay",a_279:"TP - Exit Feedback Overlay",
a_280:"TP - Editing Tips",a_281:"TP - Table of Contents",a_282:"TP - Update Tab",a_283:"TP - Link Tab",a_284:"TP - Leave Edit Mode",a_285:"TP - Submit",a_286:"TOCNav-Article Quest",a_287:"TP - Warn, Leave the Page",a_288:"TP - Warn, Stay in Page",a_289:"TP - Warn, Submit and Leave",a_290:"TOCNav-Article",a_291:"TOCNav-Recent Edits",a_292:"TOCNav-Contributors",a_293:"TOCNav-QuickFacts",a_294:"TOCNav-Biblio",a_295:"TOCNav-Websites",a_296:"TOCNav-RltdPeople",a_297:"TOCNav-RltdPlaces",a_298:"TOCNav-RltdTopics",
a_299:"TOCNav-RltdAddlInfo",a_300:"TP - Upload Overlay",a_301:"Quiz Page - Leader For This",a_302:"Quiz Page - Leader For All",a_304:"BrowImage - PopQuiz Project Promo",a_305:"TP - Project Promo",a_306:"Quiz Page - Project Promo",a_307:"List - PopQuiz Project Promo",a_308:"TP - PopQuiz Project Promo",a_309:"BrowQuiz - Project Promo",a_310:"BrowQuiz - PopQuiz Project Promo",a_311:"ImageGal - Project Promo",a_312:"ImageGal - PopQuiz Project Promo",a_313:"BrowImage - Project Promo",a_314:"List - Project Promo",
a_315:"BrowList - PopQuiz Project Promo",a_316:"BrowList - Project Promo",a_317:"Quiz Page - PopQuiz Project Promo"};if(!this.Mendel.utils)Mendel.utils={};
Mendel.utils.Browser=function(){var c=function(){return window.location.pathname},d;return{getDocumentLocation:c,setDocumentLocation:function(a){$.isUndefined(a)&&(a=c());if(!$.isFunction(d)||d(a))if($UI.browser===$UI.browser.IE&&9>$UI.browser.version){var b=document.createElement("a");b.href=a;document.body.appendChild(b);b.trigger("click")}else window.location=a},setPageRedirectionHook:function(a){d=a;if($.isUndefined(a))$UI.body.off("click.redirectionHook");else $UI.body.on("click.redirectionHook",
"a",function(b){var d=$(b.target).closest("a"),f=d.attr("target");if(!f||!("_self"!=f&&"_parent"!=f&&"_top"!=f))if(f=d.closest("[data-ytrk]"),!(f[0]&&"/"==f.attr("data-ytrk").charAt(0))&&(d=d.attr("href"),!$UIString.startsWith(d,"#")&&!$UIString.startsWith(d,c()+"#")))return b.preventDefault(),a(d),!1})},modifyCurrentUrl:function(a){window.history.replaceState&&window.history.replaceState("Object",document.title,a)},getSelectedText:function(){var a="";if(document.getSelection)a=document.getSelection();
else if(document.selection)a=document.selection.createRange().text;a=$.trim(a.toString());return""!==a?a:null},getSelectedTextPosition:function(){var a,b;if(document.selection)a=document.selection.createRange(),b={x:a.offsetLeft,y:a.offsetTop+$UI.window.scrollTop(),w:a.boundingWidth,h:a.boundingHeight};else if(document.getSelection){a=document.getSelection();var c=a.anchorOffset,d=a.focusOffset,g=$(a.anchorNode),i=g.text();b=i.substring(0,c)+'<span class="selword">'+i.substring(a.anchorOffset,d)+
"</span>"+i.substring(a.focusOffset);g=g.uiWrap("<span></span>").html(b);b=g.children(".selword");var h=b.offset();b={x:h.left,y:h.top,w:b.width(),h:b.height()};g.text(i);a.removeAllRanges();i=document.createRange();i.setStart(g[0].firstChild,c);i.setEnd(g[0].firstChild,d);a.addRange(i)}return b},removeTextSelection:function(){document.getSelection?document.getSelection().removeAllRanges():document.selection&&document.selection.empty()},playAudio:function(a){var b=$("#wav-player");$UI.isIE?(b[0]||
(b=$('<bgsound id="wav-player" />'),$UI.body.append(b)),b.attr("src",a)):$UI.browser.name===$UI.browser.FIREFOX?(b[0]||(b=$('<embed hidden="true" autostart="true" loop="1" id="wav-player" />'),$UI.body.append(b)),b.attr("src",a)):(b[0]||(b=$('<object autostart="true" type="audio/wav" id="wav-player" />'),$UI.body.append(b)),b.attr("data",a))},mqlEvent:function(a,b,c,d){var g=$UI.Utils.getBrowser();if("ie"!=g.name||"ie"==g.name&&10<=g.version)a=window.matchMedia(a),g=function(a){a.matches?b&&b():c&&
c()},a.addListener(g),d&&g(a)}}}();if(!this.Mendel.utils)Mendel.utils={};
Mendel.utils.Cookies=function(){var c=function(){var c=window.location.hostname.split(".");return"."+c[c.length-2]+"."+c[c.length-1]};return{read:function(c){for(var c=c+"=",a=null,b=document.cookie.split(";"),e=0,f=b.length;e<f;e++){for(var g=b[e];" "===g.charAt(0);)g=g.substring(1,g.length);0===g.indexOf(c)&&(a=g.substring(c.length,g.length))}return a},write:function(d,a,b){var e="";0<=b&&(e=new Date,0==b?(b=new Date("Tue, 19 Jan 2038 03:14:07 GMT"),e.setTime(b.getTime())):e.setTime(e.getTime()+
864E5*b),e="; expires="+e.toUTCString());document.cookie=d+"="+a+e+"; path=/; domain="+c()+";"},remove:function(d){document.cookie=d+"=; expires=Thu, 01-Jan-70 00:00:01 GMT; path=/; domain="+c()+";"}}}();if(!this.Mendel.utils)Mendel.utils={};
Mendel.utils.LazyLoad=function(c){for(var d=[],a=$("img",c),b=0;b<a.length;b++)d.push(a[b]);var e=function(a){var b=a.getAttribute("data-src");if(b)$(a).hide().visibility(!0).attr("src",b).removeAttr("data-src"),a.onload=function(){$(this).fadeIn("fast")}},f=function(){for(var a=0;a<d.length;a++){var b=d[a],h=b.getBoundingClientRect();if(0<=h.left&&h.left<(window.innerWidth||document.documentElement.clientWidth)&&$(b).is(":visible")||0<=h.right&&h.right<(window.innerWidth||document.documentElement.clientWidth)&&
$(b).is(":visible"))e(d[a]),d.splice(a,1)}0===d.length&&c.off("scroll touchmove",f)};c.on({scroll:f,touchmove:f});f()};
Mendel.Mbox=function(){var c={GBP:"GBP",EUR:"EUR",EMEA:"EMEA",AUD:"AUD",AUUS:"AUUSD",INR:"INR"},d=function(a,b){var c=null;try{c=mboxDefine(a,b),mboxUpdate(b)}catch(d){$log("MBOX Error: Container: ["+a+"] - mBox: ["+b+"] - Error: "+d.message)}return c};return{TYPE:{CONTENT_GIST:"mendelgist"},createOnServer:function(){for(var a=[Mendel.Mbox.TYPE.CONTENT_GIST],b="US,GBP,EUR,EMEA,AUD,AUUSD,INR".split(","),c=0;c<a.length;c++)for(var f=0;f<b.length;f++){var g=a[c]+b[f],i=d(a[c]+"-mbox",g);$log("mBox ["+
g+"] created on server: "+(null!==i?"Success":"Fail"))}},show:function(a){var b=Mendel.config.userInfo.currency,b=$.isUndefined(c[b])?"US":c[b];d(a+"-mbox",a+b)}}}();if(!this.Mendel.utils)Mendel.utils={};Mendel.utils.Meta=function(){return{getOGTags:function(){var c=[];$("meta").each(function(){var d=$(this).attr("property"),a=$(this).attr("content");d&&-1!=d.indexOf("og")&&(d=d.split(":")[1],c.hasOwnProperty(d)||(c[d]=a))});return c}}}();
Mendel.Misc=function(){return{xor:function(c,d){for(var a=[],b=0;b<c.length;b++)a.push(String.fromCharCode(d^c.charCodeAt(b)));return a.join("")},shuffle:function(c){for(var d,a,b=c.length;b;d=parseInt(Math.random()*b,10),a=c[--b],c[b]=c[d],c[d]=a);return c},getQueryStringParam:function(c,d){var a=RegExp("[?&]"+c+"=([^&]*)").exec(d||window.location.search);return a&&decodeURIComponent(a[1].replace(/\+/g," "))}}}();if(!this.Mendel.utils)Mendel.utils={};
Mendel.utils.UI=function(){var c;return{setAltBubble:function(d){c=new $UI.Popover(null,{closeButton:!1,fx:$UI.isIE&&9>$UI.browser.version?$UI.FX_NONE:$UI.FX_FADE,extraClass:"show-alt-bubble"});if(!d)d=$UI.body;$UI.isIE7&&d.find(".show-alt").each(function(){var a=$(this).findWithSelf("[alt]");a.attr("data-alt",a.attr("alt")).removeAttr("alt")});d.delegate(".show-alt","mouseenter mouseleave",function(a){if("mouseenter"==a.type){a.preventDefault();var a=$(a.target).closest(".show-alt"),b=a.userdata("show-alt");
if(!b){var d=a.findWithSelf("[alt]")[0]?"alt":"title",b={text:a.findWithSelf("["+d+"]").attr(d).replace("[",'<em class="md-media-bubble-em">').replace("]","</em>"),pos:a.hasClass("show-alt-below")?$UI.POSITION_BOTTOM:a.hasClass("show-alt-left")?$UI.POSITION_LEFT:a.hasClass("show-alt-above")?$UI.POSITION_TOP:$UI.POSITION_RIGHT};a.userdata("show-alt",b);"title"===d&&a.removeAttr("title")}""!==b.text&&c.setParameters({content:b.text,position:b.pos},a).show()}else"mouseleave"==a.type&&c.hide()})},showSlide:function(c,
a,b){c.animate(!0===a?{height:"toggle"}:{width:"toggle"},"fast");!a?c.promise().done(function(){c.children(".content").fadeIn("fast",b)}):b&&c.children(".content").fadeIn("fast",b);c.addClass("open")},hideSlide:function(c,a,b){var e=!0===a?{height:"toggle"}:{width:"toggle"};a&&(e.zIndex=101);!a?c.children(".content").fadeOut("fast").promise().done(function(){c.animate(e,"fast",b)}):c.animate(e,"fast",b);c.removeClass("open")},Dropdown:function(c,a){var a=a||"ui-dropdown",b=$('<div class="'+a+'" />'),
e=$('<div class="'+a+'-selection" />');e.on("click",function(a){c.toggle();a.stopPropagation()});c.children("li").on("click",function(){var a=this.textContent||this.innerText,b=$(this).attr("data-value")||this.value;c.trigger("change",[b]);e.text(a);$(this).toggleClass("selected",!0).siblings().toggleClass("selected",!1)});$(document).on("click",function(){c.hide()});(function(){b.addClass(function(){return c.attr("class")});c.wrap(b).removeClass().toggleClass(a+"-list",!0);e.insertBefore(c).text(c.children().first().toggleClass("selected",
!0).text())})()}}}();if(!this.Mendel.utils)Mendel.utils={};
Mendel.utils.Url=function(){return{addParameter:function(c,d,a){var b=$.isUndefined(a)?document.location.href:a,e=c+"="+d;return b=$UIString.contains(b,c+"=")?a.replace(RegExp("([?|&])"+c+"=.*?(&|$)","i"),"$1"+c+"="+d+"$2"):$UIString.contains(b,"?")?b.replace("?","?"+e+"&"):$UIString.contains(b,"#")?b.replace("#","?"+e+"#"):b+("?"+e)},removeParameter:function(c,d){var a=$.isUndefined(d)?document.location.href:d,a=a.replace(RegExp(c+"=[^#&]*"),"");$UIString.contains(a,"?#")?a=a.replace("?",""):$UIString.endsWith(a,
"?")&&(a=$UIString.chop(a));return a},getParameterValue:function(c,d){var a=$.isUndefined(d)?document.location.href:d;if($UIString.contains(a,"?"))for(var a=$UIString.after(a,"?").split("&"),b=0,e=a.length;b<e;b++){var f=a[b].split("=");if(f[0]==c)return $UIString.contains(f[1],"#")?$UIString.before(f[1],"#"):f[1]}return null}}}();