Math.uuid||function(){var a="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split("");Math.uuid=function(b,d){var c=[];d=d||a.length;if(b)for(var e=0;e<b;e++)c[e]=a[0|Math.random()*d];else{var f;c[8]=c[13]=c[18]=c[23]="-";c[14]="4";for(e=0;36>e;e++)c[e]||(f=0|16*Math.random(),c[e]=a[19==e?f&3|8:f])}return c.join("")};Math.uuidFast=function(){for(var b=Array(36),d=0,c,e=0;36>e;e++)8==e||13==e||18==e||23==e?b[e]="-":14==e?b[e]="4":(2>=d&&(d=33554432+16777216*Math.random()|0),c=d&15,
d>>=4,b[e]=a[19==e?c&3|8:c]);return b.join("")};Math.uuidCompact=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(b){var a=16*Math.random()|0;return("x"==b?a:a&3|8).toString(16)}).toUpperCase()}}();var pageReadyForStatsCalls=!1;function safeFirstPerformStatsWrite(a,b){pageReadyForStatsCalls||(pageReadyForStatsCalls=!0,performStatsWrite(a,b))}
function performStatsWriteWhenReady(a,b){document.addEventListener?DOMContentLoaded=function(){safeFirstPerformStatsWrite(a,b);document.removeEventListener("DOMContentLoaded",DOMContentLoaded,!1)}:document.attachEvent&&(DOMContentLoaded=function(){"complete"===document.readyState&&(safeFirstPerformStatsWrite(a,b),document.detachEvent("onreadystatechange",DOMContentLoaded))});"complete"===document.readyState&&setTimeout(function(){safeFirstPerformStatsWrite(a,b)},1);document.addEventListener?(document.addEventListener("DOMContentLoaded",
DOMContentLoaded,!1),window.addEventListener("load",function(){safeFirstPerformStatsWrite(a,b)},!1)):document.attachEvent&&(document.attachEvent("onreadystatechange",DOMContentLoaded),window.attachEvent("onload",function(){safeFirstPerformStatsWrite(a,b)}))}
function performStatsWrite(a,b){var d=document.getElementById("eb-stats-ctn"),c=document.createElement("img");c.setAttribute("id","eb-stat-ctn");c.setAttribute("src",buildStatUri(a,b));c.setAttribute("width","1px");c.setAttribute("height","1px");c.style.display="none";d?document.getElementsByTagName("body")[0].replaceChild(c,d):document.getElementsByTagName("body")[0].appendChild(c)}function writeStat(a,b){pageReadyForStatsCalls?performStatsWrite(a,b):performStatsWriteWhenReady(a,b)}
function buildStatUri(a,b){return(b&&b.hostnameOverride?document.location.protocol+"//"+b.hostnameOverride+"/webstats/stats.gif?":"/webstats/stats.gif?")+buildStatQuery(a,b)}
function buildStatQuery(a,b){var d=[],c={a:getAccountId(a),ac:" ",d:document.domain,od:" ",h:getHitCount(),rf:document.referrer,rq:document.location.href,s:getSessionId(),json:" "};b&&(b.accountId&&(c.a=b.accountId),b.domain&&(c.od=b.domain),b.hitCount&&(c.h=b.hitCount),b.referrerUrl&&(c.rf=b.referrerUrl),b.requestUrl&&(c.rq=b.requestUrl),b.json&&(c.json=b.json));a&&(c.ac=a);for(var e in c)c.hasOwnProperty(e)&&d.push(encodeURIComponent(e)+"="+encodeURIComponent(c[e]));return d.join("&")}
function getHitCount(){var a;a=1+document.embeds.length;a+=document.getElementsByTagName("object").length;a+=document.images.length;a+=document.styleSheets.length;return a=document.scripts?a+document.scripts.length:a+document.getElementsByTagName("script").length}function setSessionIdCookie(){var a=Math.uuid();cookie("sessionId",a,{expires:10,raw:!0});return a}
function cookie(a,b,d){if(1<arguments.length&&"[object Object]"!==String(b)){if(null===b||void 0===b)d.expires=-1;if("number"===typeof d.expires){var c=d.expires,e=d.expires=new Date;e.setMinutes(e.getMinutes()+c)}b=String(b);return document.cookie=[encodeURIComponent(a),"=",d.raw?b:encodeURIComponent(b),d.expires?"; expires="+d.expires.toUTCString():"",d.path?"; path="+d.path:"",d.domain?"; domain="+d.domain:"",d.secure?"; secure":""].join("")}d=b||{};e=d.raw?function(a){return a}:decodeURIComponent;
return(c=RegExp("(?:^|; )"+encodeURIComponent(a)+"=([^;]*)").exec(document.cookie))?e(c[1]):null}function getAccountId(a){a=cookie(a);return null===a?-1:a}function getSessionId(){var a=cookie("sessionId");return null===a?setSessionIdCookie():a};
